CREATE TABLE Sett (
 id NUMBER(20, 0), 
 sort NUMBER(2, 0) NOT NULL, 
 created DATE NOT NULL, 
 creator_id NUMBER(20) NOT NULL, 
 modified DATE NOT NULL, 
 description VARCHAR2(256), 
 CONSTRAINT sett_pk PRIMARY KEY (id) ENABLE, 
 CONSTRAINT sett_setsort_fk FOREIGN KEY (sort)
  REFERENCES SetSort(id) ON DELETE CASCADE ENABLE
);

CREATE SEQUENCE sett_seq ORDER;
