package com.syrus.AMFICOM.map;


/**
* com/syrus/AMFICOM/map/ComSyrusAmficomMapScheme.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-map.idl
* 4 Март 2005 г. 18:11:08 MSK
*/

public interface ComSyrusAmficomMapScheme
{
  public abstract com.syrus.AMFICOM.map.corba.Map_Transferable map ();

  public abstract void map (com.syrus.AMFICOM.map.corba.Map_Transferable newMap);

  public abstract Map mapImpl ();

  public abstract void mapImpl (Map newMapImpl);

} // interface ComSyrusAmficomMapScheme
