package com.syrus.AMFICOM.map;


/**
* com/syrus/AMFICOM/map/ComSyrusAmficomMapSchemeLink.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-map.idl
* 4 Март 2005 г. 18:11:09 MSK
*/

public interface ComSyrusAmficomMapSchemeLink
{
  public abstract com.syrus.AMFICOM.map.corba.SiteNode_Transferable siteNode ();

  public abstract void siteNode (com.syrus.AMFICOM.map.corba.SiteNode_Transferable newSiteNode);

  public abstract SiteNode siteNodeImpl ();

  public abstract void siteNodeImpl (SiteNode newSiteNodeImpl);

} // interface ComSyrusAmficomMapSchemeLink
