package com.syrus.AMFICOM.map;


/**
* com/syrus/AMFICOM/map/ComSyrusAmficomMapCableChannelingItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-map.idl
* 4 Март 2005 г. 18:11:08 MSK
*/

public interface ComSyrusAmficomMapCableChannelingItem
{
  public abstract com.syrus.AMFICOM.map.corba.PhysicalLink_Transferable physicalLink ();

  public abstract void physicalLink (com.syrus.AMFICOM.map.corba.PhysicalLink_Transferable newPhysicalLink);

  public abstract PhysicalLink physicalLinkImpl ();

  public abstract void physicalLinkImpl (PhysicalLink newPhysicalLinkImpl);

  public abstract com.syrus.AMFICOM.map.corba.SiteNode_Transferable startSiteNode ();

  public abstract void startSiteNode (com.syrus.AMFICOM.map.corba.SiteNode_Transferable newStartSiteNode);

  public abstract SiteNode startSiteNodeImpl ();

  public abstract void startSiteNodeImpl (SiteNode newStartSiteNodeImpl);

  public abstract com.syrus.AMFICOM.map.corba.SiteNode_Transferable endSiteNode ();

  public abstract void endSiteNode (com.syrus.AMFICOM.map.corba.SiteNode_Transferable newEndSiteNode);

  public abstract SiteNode endSiteNodeImpl ();

  public abstract void endSiteNodeImpl (SiteNode newEndSiteNodeImpl);

} // interface ComSyrusAmficomMapCableChannelingItem
