package com.syrus.AMFICOM.scheme.corba.PathElementPackage;


/**
* com/syrus/AMFICOM/scheme/corba/PathElementPackage/Type.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public class Type implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static com.syrus.AMFICOM.scheme.corba.PathElementPackage.Type[] __array = new com.syrus.AMFICOM.scheme.corba.PathElementPackage.Type [__size];

  public static final int _SCHEME_CABLE_LINK = 0;
  public static final com.syrus.AMFICOM.scheme.corba.PathElementPackage.Type SCHEME_CABLE_LINK = new com.syrus.AMFICOM.scheme.corba.PathElementPackage.Type(_SCHEME_CABLE_LINK);
  public static final int _SCHEME_ELEMENT = 1;
  public static final com.syrus.AMFICOM.scheme.corba.PathElementPackage.Type SCHEME_ELEMENT = new com.syrus.AMFICOM.scheme.corba.PathElementPackage.Type(_SCHEME_ELEMENT);
  public static final int _SCHEME_LINK = 2;
  public static final com.syrus.AMFICOM.scheme.corba.PathElementPackage.Type SCHEME_LINK = new com.syrus.AMFICOM.scheme.corba.PathElementPackage.Type(_SCHEME_LINK);

  public int value ()
  {
    return __value;
  }

  public static com.syrus.AMFICOM.scheme.corba.PathElementPackage.Type from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Type (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Type
