/*
 * $Id: alarm.idl,v 1.1 2004/06/22 12:27:24 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Научно-технический центр.
 * Проект: АМФИКОМ.
 */

#ifndef ALARM_IDL
#define ALARM_IDL

#include <common.idl>

/**
 * @version $Revision: 1.1 $, $Date: 2004/06/22 12:27:24 $
 * @author $Author: bass $
 */
module com {
	module syrus {
		module AMFICOM {
			module corba {
				module portable {
					module alarm {
						valuetype Message {
							private ::com::syrus::AMFICOM::corba::portable::common::Identifier alertingId;
							private ::com::syrus::AMFICOM::corba::portable::common::Identifier messageTypeId;
							private ::com::syrus::AMFICOM::corba::portable::common::Identifier eventId;
							private long long eventDate;
							private wstring<258> eventSourceName;
							private wstring<1024> eventSourceDescription;
							private wstring<128> transmissionPathName;
							private wstring<4000> transmissionPathDescription;
							private wstring<4000> text;
							::com::syrus::AMFICOM::corba::portable::common::Identifier getAlertingId();
							::com::syrus::AMFICOM::corba::portable::common::Identifier getMessageTypeId();
							::com::syrus::AMFICOM::corba::portable::common::Identifier getEventId();
							long long getEventDate();
							wstring<258> getEventSourceName();
							wstring<1024> getEventSourceDescription();
							wstring<128> getTransmissionPathName();
							wstring<4000> getTransmissionPathDescription();
							wstring<4000> getText();
						};

						typedef sequence<Message> MessageSeq;
					};
				};
			};
		};
	};
};

#endif
