/*
 * $Id: client.idl,v 1.1 2004/06/22 12:27:24 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Научно-технический центр.
 * Проект: АМФИКОМ.
 */

#ifndef CLIENT_IDL
#define CLIENT_IDL

#include <alarm.idl>

/**
 * @version $Revision: 1.1 $, $Date: 2004/06/22 12:27:24 $
 * @author $Author: bass $
 */
module com {
	module syrus {
		module AMFICOM {
			module corba {
				module portable {
					module client {
						interface Client {
							void syncPing(out long long clientTimeMillis);

							void reportPopupMessages(in com::syrus::AMFICOM::corba::portable::alarm::MessageSeq messageSeq)
								raises (com::syrus::AMFICOM::corba::portable::common::MessageDeliveryFailedException);
						};

						typedef sequence<Client> ClientSeq;
					};
				};
			};
		};
	};
};

#endif
