/*
 * $Id: common.idl,v 1.2 2004/09/24 10:13:01 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Научно-технический центр.
 * Проект: АМФИКОМ.
 */

#ifndef COMMON_IDL
#define COMMON_IDL

#define PORTABLE_THROWABLE_BODY \
	wstring reason;\
	PortableStackTraceElementSeq stackTrace;

/**
 * @version $Revision: 1.2 $, $Date: 2004/09/24 10:13:01 $
 * @author $Author: bass $
 */
module com {
	module syrus {
		module AMFICOM {
			module corba {
				module portable {
					module common {
						valuetype Identifier {
							private string<64> id;
						};

						typedef sequence<Identifier> IdentifierSeq;

						struct PortableStackTraceElement {
							string declaringClass;
							string methodName;
							string fileName;
							long lineNumber;
						};

						typedef sequence<PortableStackTraceElement> PortableStackTraceElementSeq;

						exception MessageDeliveryFailedException {
							PORTABLE_THROWABLE_BODY
						};

						typedef sequence<MessageDeliveryFailedException> MessageDeliveryFailedExceptionSeq;

						exception DatabaseAccessException {
							PORTABLE_THROWABLE_BODY
							string sqlState;
							long vendorCode;
							sequence<DatabaseAccessException> next;
						};

						typedef sequence<DatabaseAccessException> DatabaseAccessExceptionSeq;
					};
				};
			};
		};
	};
};

#endif
