/*
 * $Id: constants.idl,v 1.1 2005/05/04 10:42:41 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Научно-технический центр.
 * Проект: АМФИКОМ.
 */

#ifndef CONSTANTS_IDL
#define CONSTANTS_IDL

module com {
module syrus {
module AMFICOM {
module corba {
module portable {
module constants {
	abstract valuetype AlarmTypeConstants {
		const string ID_RTU_HW_ALARM = "rtuhwalarm";
		const string ID_RTU_SW_ALARM = "rtuswalarm";
		const string ID_RTU_TEST_ALARM = "rtutestalarm";
		const string ID_RTU_TEST_WARNING = "rtutestwarning";
	};

	abstract valuetype EventTypeConstants {
		const string ID_ALARM_CHANGE_EVENT = "alarmchangeevent";
		const string ID_ALARM_EVENT = "alarmevent";
		const string ID_ALERT_EVENT = "alertevent";
		const string ID_ANALYSE_EVENT = "analyseevent";
		const string ID_CHANGE_EVENT = "changeevent";
		const string ID_CONNECT_EVENT = "connectevent";
		const string ID_CONNECT_PORT_EVENT = "connectportevent";
		const string ID_DISCONNECT_EVENT = "disconnectevent";
		const string ID_DISCONNECT_PORT_EVENT = "disconnectportevent";
		const string ID_EVALUATE_EVENT = "evaluateevent";
		const string ID_EVALUATION_ALARM_EVENT = "evaluationalarmevent";
		const string ID_EVALUATION_WARNING_EVENT = "evaluationwarningevent";
		const string ID_HW_ALARM_EVENT = "hwalarmevent";
		const string ID_LOGIN_EVENT = "loginevent";
		const string ID_LOGOFF_EVENT = "logoffevent";
		const string ID_READ_EVENT = "readevent";
		const string ID_RESULT_EVENT = "resultevent";
		const string ID_SW_ALARM_EVENT = "swalarmevent";
		const string ID_SWITCH_OFF_EVENT = "switchoffevent";
		const string ID_SWITCH_ON_EVENT = "switchonevent";
		const string ID_TEST_ALARM_EVENT = "testalarmevent";
		const string ID_TEST_WARNING_EVENT = "testwarningevent";
		const string ID_TIMER_EVENT = "timerevent";
		const string ID_WRITE_EVENT = "writeevent";
	};

	abstract valuetype MessageTypeConstants {
		const string ID_ALARM = "alarm";
		const string ID_CRITICAL = "critical";
		const string ID_DIAGNOSTICS = "diagnostics";
		const string ID_ERROR = "error";
		const string ID_INFO = "info";
		const string ID_WARNING = "warning";
	};
};
};
};
};
};
};

#endif // CONSTANTS_IDL
