#ifndef _MCM_IDL_
#define _MCM_IDL_

#include <measurement.idl>
#include <configuration.idl>

module com {
module syrus {
module AMFICOM {
module mcm {
module corba {

	interface MCM {

		void receiveTests(in com::syrus::AMFICOM::measurement::corba::TestSeq_Transferable tests)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		void abortTest(in com::syrus::AMFICOM::general::corba::Identifier_Transferable test_id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::Measurement_Transferable transmitMeasurement(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::Analysis_Transferable transmitAnalysis(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::Evaluation_Transferable transmitEvaluation(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		void ping(in long i)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
	};

};
};
};
};
};

#endif
