/*-
 * $Id: administration.idl,v 1.27.2.1 2006/06/09 15:56:34 arseniy Exp $
 *
 * Copyright ¿ 2004-2005 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef ADMINISTRATION_IDL
#define ADMINISTRATION_IDL

#include "general.idl"

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
module com {
module syrus {
module AMFICOM {
#else // MY_COMPILER_IS_NOT_BRAINDEAD
#pragma prefix "AMFICOM.syrus.com"
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

module administration {
	module corba {


//////////////////////////////////// DomainMember /////////////////////////////////

		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlDomainMember : general::corba::IdlStorableObject {
			public general::corba::IdlIdentifier domainId;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in general::corba::IdlIdentifier domainId);
		};


//////////////////////////////////// Role /////////////////////////////////
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlRole : general::corba::IdlStorableObject {
			
			public general::corba::WString32 codename;
			public general::corba::WString256 description;
			public general::corba::IdlIdentifierSeq systemUserIds;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in general::corba::WString32 codename,
					in general::corba::WString256 description,
					in general::corba::IdlIdentifierSeq systemUserIds);
		};


//////////////////////////////////// SystemUser /////////////////////////////////

		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlSystemUser : general::corba::IdlStorableObject {
			/*\u002a\u002f@SuppressWarnings("all")/**/
			enum SystemUserSort {
				USER_SORT_SYSADMIN,
				USER_SORT_REGULAR,
				USER_SORT_SERVERPROCESS,
				USER_SORT_MCM
			};

			public general::corba::WString32 login;
			public SystemUserSort sort;
			public general::corba::WString128 name;
			public general::corba::WString256 description;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in general::corba::WString32 login,
					in SystemUserSort sort,
					in general::corba::WString128 name,
					in general::corba::WString256 description);
		};

//////////////////////////////////// PermissionAttributes /////////////////////////////////

		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlPermissionAttributes : general::corba::IdlStorableObject {
			/*\u002a\u002f@SuppressWarnings("all")/**/
			enum IdlModule {
				ADMINISTRATION,
				SCHEME,
				ELEMENTS_EDITOR,
				MAP_EDITOR,
				OPTIMIZATION,
				MODELING,
				SCHEDULER,
				ANALYSIS,
				RESEARCH,
				EVALUATION,
				OBSERVE,
				PREDICTION,
				REPORT
			};

			public general::corba::IdlIdentifier domainId;			
			public general::corba::IdlIdentifier userId;			
			public IdlModule _module;
			public ::CORBA::OctetSeq permissionMask;
			public ::CORBA::OctetSeq denyMask;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in general::corba::IdlIdentifier domainId,
					in general::corba::IdlIdentifier userId,
					in IdlModule _module,
					in ::CORBA::OctetSeq permissionMask,
					in ::CORBA::OctetSeq denyMask);
		};


/////////////////////////////////// Domain ////////////////////////////////

		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlDomain : IdlDomainMember {
			public general::corba::WString128 name;
			public general::corba::WString256 description;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in general::corba::IdlIdentifier domainId,
					in general::corba::WString128 name,
					in general::corba::WString256 description);
		};
		
		/*\u002a\u002f@SuppressWarnings("all")/**/
		typedef sequence<IdlDomain> IdlDomainSeq;


/////////////////////////////////// Server ////////////////////////////////

		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlServer : IdlDomainMember {
			public general::corba::WString128 name;
			public general::corba::WString256 description;
			public general::corba::WString64 hostname;
			public general::corba::IdlIdentifier systemUserId;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in general::corba::IdlIdentifier domainId,
					in general::corba::WString128 name,
					in general::corba::WString256 description,
					in general::corba::WString64 hostname,
					in general::corba::IdlIdentifier systemUserId);
		};


//////////////////////////////////// MCM //////////////////////////////////

		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlMCM : IdlDomainMember {
			public general::corba::WString128 name;
			public general::corba::WString256 description;
			public general::corba::WString64 hostname;
			public general::corba::IdlIdentifier systemUserId;
			public general::corba::IdlIdentifier serverId;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in general::corba::IdlIdentifier domainId,
					in general::corba::WString128 name,
					in general::corba::WString256 description,
					in general::corba::WString64 hostname,
					in general::corba::IdlIdentifier systemUserId,
					in general::corba::IdlIdentifier serverId);
		};


//////////////////////////////// ServerProcess ////////////////////////////

		/*\u002a\u002f@SuppressWarnings("all")/**/
		/*\u002a\u002f@Deprecated/**/
		valuetype IdlServerProcess : general::corba::IdlStorableObject {
			public general::corba::WString32 codename;
			public general::corba::IdlIdentifier serverId;
			public general::corba::IdlIdentifier userId;
			public general::corba::WString256 description;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in general::corba::WString32 codename,
					in general::corba::IdlIdentifier serverId,
					in general::corba::IdlIdentifier userId,
					in general::corba::WString256 description);
		};

	};
};

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
};
};
};
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

#endif // ADMINISTRATION_IDL
