/*-
 * $Id: alarm.idl,v 1.12 2005/07/10 13:49:38 bass Exp $
 *
 * Copyright ¿ 2004-2005 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef ALARM_IDL
#define ALARM_IDL

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
module com {
module syrus {
module AMFICOM {
#else // MY_COMPILER_IS_NOT_BRAINDEAD
#pragma prefix "AMFICOM.syrus.com"
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

module event {
	module corba {
		enum AlarmStatus {
			ALARM_STATUS_GENERATED,
			ALARM_STATUS_ASSIGNED,
			ALARM_STATUS_FIXED,
			ALARM_STATUS_DELETED
		};

		enum EventStatus {
			EVENT_STATUS_GENERATED,
			EVENT_STATUS_PROCESSED
		};
	};
};

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
};
};
};
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

#endif // ALARM_IDL
