/*-
 * $Id: arserver.idl,v 1.19 2005/05/27 16:24:46 bass Exp $
 *
 * Copyright ¿ 2004-2005 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef ARSERVER_IDL
#define ARSERVER_IDL

#include "configuration.idl"
#include "resource.idl"

module com {
	module syrus {
		module AMFICOM {
			module arserver {
				module corba {
					interface ARServer: general::corba::CommonServer {
						general::corba::StorableObjectSeq receiveImageResources(
								in resource::corba::ImageResourceSeq imageResources,
								in boolean force,
								in security::corba::SessionKey sessionKey)						 		   
							raises (general::corba::AMFICOMRemoteException);

						resource::corba::ImageResourceSeq transmitImageResources(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
							raises (general::corba::AMFICOMRemoteException);

						resource::corba::ImageResourceSeq transmitImageResourcesButIdsCondition(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey,
								in general::corba::StorableObjectCondition condition)
							raises (general::corba::AMFICOMRemoteException);
					};
				};
			};
		};
	};
};

#endif // ARSERVER_IDL
