/*
 * $Id: client.idl,v 1.5 2004/12/23 12:30:42 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Научно-технический центр.
 * Проект: АМФИКОМ.
 */

#ifndef CLIENT_IDL
#define CLIENT_IDL

#include "alarm.idl"

module com {
	module syrus {
		module AMFICOM {
			module CORBA {
				module General {
					exception AMFICOMRemoteException {
						long code;
						wstring message;
					};
				};

				interface AMFICOMClient {
					void syncPing(
						out long long clientTimeMillis)
						raises (General::AMFICOMRemoteException);

					void reportMessage(
						in Alarm::MessageSeq_Transferable messages)
						raises (General::AMFICOMRemoteException);
				};
			};
		};
	};
};

#endif
