#ifndef _CMSERVER_IDL_
#define _CMSERVER_IDL_

#include <general.idl>
#include <administration.idl>
#include <measurement.idl>
#include <configuration.idl>

module com {
module syrus {
module AMFICOM {
module cmserver {
module corba {

	interface CMServer:
		general::corba::NameResolver,
		general::corba::IdentifierGeneratorServer {

		void delete(in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
				raises (general::corba::AMFICOMRemoteException);

		void deleteList(in general::corba::IdentifierSeq_Transferable id_Transferables,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
				raises (general::corba::AMFICOMRemoteException);

/////////////////////////////////////////// General Recieve ////////////////////////////////////////////		
		void receiveParameterType(in general::corba::ParameterType_Transferable parameterType_Transferable,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveParameterTypes(in general::corba::ParameterTypeSeq_Transferable sets,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveCharacteristicType(in general::corba::CharacteristicType_Transferable characteristicType_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveCharacteristicTypes(in general::corba::CharacteristicTypeSeq_Transferable characteristicTypes_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveCharacteristic(in general::corba::Characteristic_Transferable characteristic_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveCharacteristics(in general::corba::CharacteristicSeq_Transferable characteristics_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

/////////////////////////////////////////// Administration Recieve ////////////////////////////////////////////
		void receiveUser(in administration::corba::User_Transferable User_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveUsers(in administration::corba::UserSeq_Transferable users_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveDomain(in administration::corba::Domain_Transferable domain_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveDomains(in administration::corba::DomainSeq_Transferable domains_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveServer(in administration::corba::Server_Transferable server_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveServers(in administration::corba::ServerSeq_Transferable servers_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMCM(in administration::corba::MCM_Transferable mcm_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMCMs(in administration::corba::MCMSeq_Transferable mcms_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

/////////////////////////////////////////// Configuration Recieve ////////////////////////////////////////////
		void receiveCableThreadType(in configuration::corba::CableThreadType_Transferable cableThreadType_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveCableThreadTypes(in configuration::corba::CableThreadTypeSeq cableThreadTypes_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveEquipment(in configuration::corba::Equipment_Transferable equipment_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveEquipments(in configuration::corba::EquipmentSeq_Transferable equipments_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveEquipmentType(in configuration::corba::EquipmentType_Transferable equipmentType_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveEquipmentTypes(in configuration::corba::EquipmentTypeSeq_Transferable equipmentTypes_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveKIS(in configuration::corba::KIS_Transferable kis_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveKISs(in configuration::corba::KISSeq_Transferable kiss_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);			

		void receiveLink(in configuration::corba::Link_Transferable link_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveLinks(in configuration::corba::LinkSeq_Transferable link_Transferables,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveLinkType(in configuration::corba::LinkType_Transferable linkType_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveLinkTypes(in configuration::corba::AbstractLinkTypeSeq_Transferable linkType_Transferables,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMeasurementPort(in configuration::corba::MeasurementPort_Transferable measurementPort_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMeasurementPorts(in configuration::corba::MeasurementPortSeq_Transferable measurementPorts_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMeasurementPortType(in configuration::corba::MeasurementPortType_Transferable measurementPortType_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMeasurementPortTypes(in configuration::corba::MeasurementPortTypeSeq_Transferable measurementPortTypes_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMonitoredElement(in configuration::corba::MonitoredElement_Transferable monitoredElement_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMonitoredElements(in configuration::corba::MonitoredElementSeq_Transferable monitoredElements_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receivePort(in configuration::corba::Port_Transferable port_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receivePorts(in configuration::corba::PortSeq_Transferable ports_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receivePortType(in configuration::corba::PortType_Transferable portType_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receivePortTypes(in configuration::corba::PortTypeSeq_Transferable portTypes_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveTransmissionPath(in configuration::corba::TransmissionPath_Transferable transmissionPath_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveTransmissionPaths(in configuration::corba::TransmissionPathSeq_Transferable transmissionPaths_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveTransmissionPathType(in configuration::corba::TransmissionPathType_Transferable transmissionPathType_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveTransmissionPathTypes(in configuration::corba::TransmissionPathTypeSeq_Transferable transmissionPathTypes_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

//////////////////////////////////////////// Measurement Receive //////////////////////////////////////////////
		void receiveAnalysis(in measurement::corba::Analysis_Transferable analysis_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveAnalyses(in measurement::corba::AnalysisSeq_Transferable sets,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveAnalysisType(in measurement::corba::AnalysisType_Transferable analysisType_Transferable,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveAnalysisTypes(in measurement::corba::AnalysisTypeSeq_Transferable sets,
						in boolean force, 	
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveEvaluation(in measurement::corba::Evaluation_Transferable evaluation_Transferable,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveEvaluations(in measurement::corba::EvaluationSeq_Transferable sets,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveEvaluationType(in measurement::corba::EvaluationType_Transferable evaluationType_Transferable,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveEvaluationTypes(in measurement::corba::EvaluationTypeSeq_Transferable sets,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMeasurement(in measurement::corba::Measurement_Transferable measurement_Transferable,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMeasurements(in measurement::corba::MeasurementSeq_Transferable sets,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMeasurementSetup(in measurement::corba::MeasurementSetup_Transferable measurementSetup_Transferable,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMeasurementSetups(in measurement::corba::MeasurementSetupSeq_Transferable sets,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMeasurementType(in measurement::corba::MeasurementType_Transferable measurementType_Transferable,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveMeasurementTypes(in measurement::corba::MeasurementTypeSeq_Transferable sets,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveModeling(in measurement::corba::Modeling_Transferable modeling_Transferable,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveModelings(in measurement::corba::ModelingSeq_Transferable sets,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveResult(in measurement::corba::Result_Transferable result_Transferable,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveResults(in measurement::corba::ResultSeq_Transferable sets,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveSet(in measurement::corba::Set_Transferable set_Transferable,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveSets(in measurement::corba::SetSeq_Transferable sets,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveTemporalPattern(in measurement::corba::TemporalPattern_Transferable temporalPattern_Transferable,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);
			
		void receiveTemporalPatterns(in measurement::corba::TemporalPatternSeq_Transferable sets,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		void receiveTest(in measurement::corba::Test_Transferable test_Transferable,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);	

		void receiveTests(in measurement::corba::TestSeq_Transferable tests,
						in boolean force,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);


//////////////////////////////////////////// General Transmit //////////////////////////////////////////////////
		general::corba::ParameterType_Transferable transmitParameterType(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);	

		general::corba::CharacteristicType_Transferable transmitCharacteristicType(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		general::corba::Characteristic_Transferable transmitCharacteristic(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);


		// Transmit Sequences

		general::corba::ParameterTypeSeq_Transferable transmitParameterTypes(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		general::corba::ParameterTypeSeq_Transferable transmitParameterTypesButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		general::corba::ParameterTypeSeq_Transferable transmitParameterTypesButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in general::corba::StringFieldCondition_Transferable stringFieldCondition_Transferable)
			raises (general::corba::AMFICOMRemoteException);

		general::corba::CharacteristicSeq_Transferable transmitCharacteristics(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		general::corba::CharacteristicSeq_Transferable transmitCharacteristicsButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		general::corba::CharacteristicSeq_Transferable transmitCharacteristicsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in general::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable)
			raises (general::corba::AMFICOMRemoteException);

		general::corba::CharacteristicTypeSeq_Transferable transmitCharacteristicTypes(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		general::corba::CharacteristicTypeSeq_Transferable transmitCharacteristicTypesButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);


		// Reftresh Storable objects in Pool
		general::corba::IdentifierSeq_Transferable transmitRefreshedGeneralObjects(
						in general::corba::StorableObjectSeq_Transferable StorableObjects_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

///////////////////////////////////////// Administration Transmit //////////////////////////////////////////////

		administration::corba::User_Transferable transmitUser(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::Domain_Transferable transmitDomain(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::Server_Transferable transmitServer(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::MCM_Transferable transmitMCM(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);


		// Transmit Sequences
		administration::corba::UserSeq_Transferable transmitUsers(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::UserSeq_Transferable transmitUsersButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in general::corba::StringFieldCondition_Transferable stringFieldCondition)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::DomainSeq_Transferable transmitDomains(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::DomainSeq_Transferable transmitDomainsButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::DomainSeq_Transferable transmitDomainsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::ServerSeq_Transferable transmitServers(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::ServerSeq_Transferable transmitServersButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::ServerSeq_Transferable transmitServersButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::MCMSeq_Transferable transmitMCMs(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::MCMSeq_Transferable transmitMCMsButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		administration::corba::MCMSeq_Transferable transmitMCMsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);


		// Reftresh Storable objects in Pool
		general::corba::IdentifierSeq_Transferable transmitRefreshedAdministrationObjects(
						in general::corba::StorableObjectSeq_Transferable StorableObjects_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

///////////////////////////////////////// Configuration Transmit ///////////////////////////////////////////////

		configuration::corba::CableThreadType_Transferable transmitCableThreadType(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::Equipment_Transferable transmitEquipment(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::EquipmentType_Transferable transmitEquipmentType(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::KIS_Transferable transmitKIS(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);				

		configuration::corba::Link_Transferable transmitLink(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::LinkType_Transferable transmitLinkType(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::MeasurementPort_Transferable transmitMeasurementPort(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::MeasurementPortType_Transferable transmitMeasurementPortType(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::MonitoredElement_Transferable transmitMonitoredElement(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::Port_Transferable transmitPort(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::PortType_Transferable transmitPortType(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::TransmissionPath_Transferable transmitTransmissionPath(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::TransmissionPathType_Transferable transmitTransmissionPathType(
						in general::corba::Identifier_Transferable id_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);


					// Transmit Sequences		

		configuration::corba::CableThreadTypeSeq transmitCableThreadTypes(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::CableThreadTypeSeq transmitCableThreadTypesButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::EquipmentSeq_Transferable transmitEquipments(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::EquipmentSeq_Transferable transmitEquipmentsButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::EquipmentSeq_Transferable transmitEquipmentsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::EquipmentTypeSeq_Transferable transmitEquipmentTypes(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::EquipmentTypeSeq_Transferable transmitEquipmentTypesButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::KISSeq_Transferable transmitKISs(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::KISSeq_Transferable transmitKISsButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::KISSeq_Transferable transmitKISsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);		

		configuration::corba::LinkSeq_Transferable transmitLinks(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::LinkSeq_Transferable transmitLinksButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::AbstractLinkTypeSeq_Transferable transmitLinkTypes(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::AbstractLinkTypeSeq_Transferable transmitLinkTypesButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::MeasurementPortSeq_Transferable transmitMeasurementPorts(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::MeasurementPortSeq_Transferable transmitMeasurementPortsButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::MeasurementPortSeq_Transferable transmitMeasurementPortsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::MeasurementPortTypeSeq_Transferable transmitMeasurementPortTypes(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::MeasurementPortTypeSeq_Transferable transmitMeasurementPortTypesButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::MonitoredElementSeq_Transferable transmitMonitoredElements(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::MonitoredElementSeq_Transferable transmitMonitoredElementsButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::MonitoredElementSeq_Transferable transmitMonitoredElementsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::PortSeq_Transferable transmitPorts(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::PortSeq_Transferable transmitPortsButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::PortSeq_Transferable transmitPortsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::PortTypeSeq_Transferable transmitPortTypes(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::PortTypeSeq_Transferable transmitPortTypesButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::TransmissionPathSeq_Transferable transmitTransmissionPaths(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::TransmissionPathSeq_Transferable transmitTransmissionPathsButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::TransmissionPathSeq_Transferable transmitTransmissionPathsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::TransmissionPathTypeSeq_Transferable transmitTransmissionPathTypes(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		configuration::corba::TransmissionPathTypeSeq_Transferable transmitTransmissionPathTypesButIds(
						in general::corba::IdentifierSeq_Transferable ids_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);


		// Reftresh Storable objects in Pool
		general::corba::IdentifierSeq_Transferable transmitRefreshedConfigurationObjects(
						in general::corba::StorableObjectSeq_Transferable StorableObjects_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

///////////////////////////////////////// Measurement Transmit ///////////////////////////////////////////////

					// Transmit one object
		measurement::corba::AnalysisType_Transferable transmitAnalysisType(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);			

		measurement::corba::EvaluationType_Transferable transmitEvaluationType(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::MeasurementType_Transferable transmitMeasurementType(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);			

		measurement::corba::Analysis_Transferable transmitAnalysis(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::Evaluation_Transferable transmitEvaluation(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::Modeling_Transferable transmitModeling(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::Measurement_Transferable transmitMeasurement(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);		

		measurement::corba::MeasurementSetup_Transferable transmitMeasurementSetup(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);						

		measurement::corba::Result_Transferable transmitResult(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);				

		measurement::corba::Set_Transferable transmitSet(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);				

		measurement::corba::TemporalPattern_Transferable transmitTemporalPattern(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::Test_Transferable transmitTest(
						in general::corba::Identifier_Transferable id,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);					


					// Transmit Sequences		

		measurement::corba::AnalysisTypeSeq_Transferable transmitAnalysisTypes(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::AnalysisTypeSeq_Transferable transmitAnalysisTypesButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)			
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::AnalysisTypeSeq_Transferable transmitAnalysisTypesButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in general::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable)			
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::EvaluationTypeSeq_Transferable transmitEvaluationTypes(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::EvaluationTypeSeq_Transferable transmitEvaluationTypesButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::EvaluationTypeSeq_Transferable transmitEvaluationTypesButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in general::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable)
			raises (general::corba::AMFICOMRemoteException);						

		measurement::corba::MeasurementTypeSeq_Transferable transmitMeasurementTypes(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::MeasurementTypeSeq_Transferable transmitMeasurementTypesButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::MeasurementTypeSeq_Transferable transmitMeasurementTypesButIdsLinkedIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in general::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::MeasurementTypeSeq_Transferable transmitMeasurementTypesButIdsStringFieldCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in general::corba::StringFieldCondition_Transferable stringFieldCondition_Transferable)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::AnalysisSeq_Transferable transmitAnalyses(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::AnalysisSeq_Transferable transmitAnalysesButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::AnalysisSeq_Transferable transmitAnalysesButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)			
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::EvaluationSeq_Transferable transmitEvaluations(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::EvaluationSeq_Transferable transmitEvaluationsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::EvaluationSeq_Transferable transmitEvaluationsButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::ModelingSeq_Transferable transmitModelings(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::ModelingSeq_Transferable transmitModelingsButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::ModelingSeq_Transferable transmitModelingsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::MeasurementSeq_Transferable transmitMeasurements(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::MeasurementSeq_Transferable transmitMeasurementsButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::MeasurementSeq_Transferable transmitMeasurementsButIdsLinkedCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in general::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable)			
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::MeasurementSeq_Transferable transmitMeasurementsButIdsDomainCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)			
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::MeasurementSetupSeq_Transferable transmitMeasurementSetups(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::MeasurementSetupSeq_Transferable transmitMeasurementSetupsButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);			

		measurement::corba::MeasurementSetupSeq_Transferable transmitMeasurementSetupsButIdsLinkedCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in general::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable)
			raises (general::corba::AMFICOMRemoteException);			

		measurement::corba::ResultSeq_Transferable transmitResults(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::ResultSeq_Transferable transmitResultsButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::ResultSeq_Transferable transmitResultsButIdsDomainCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::ResultSeq_Transferable transmitResultsButIdsLinkedCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in general::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::ResultSeq_Transferable transmitResultsButIdsResultCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in measurement::corba::ResultCondition_Transferable resultCondition_Transferable)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::ResultSeq_Transferable transmitResultsButIdsResultSortCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in measurement::corba::ResultSortCondition_Transferable resultSortCondition_Transferable)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::SetSeq_Transferable transmitSets(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::SetSeq_Transferable transmitSetsButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::SetSeq_Transferable transmitSetsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in administration::corba::DomainCondition_Transferable domainCondition)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::TemporalPatternSeq_Transferable transmitTemporalPatterns(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::TemporalPatternSeq_Transferable transmitTemporalPatternsButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);						

		measurement::corba::TestSeq_Transferable transmitTests(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::TestSeq_Transferable transmitTestsButIds(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException);

		measurement::corba::TestSeq_Transferable transmitTestsButIdsCondition(
						in general::corba::IdentifierSeq_Transferable ids,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier,
						in measurement::corba::TemporalCondition_Transferable temporalCondition_Transferable)
			raises (general::corba::AMFICOMRemoteException);	


		// Reftresh Storable objects in Pool
		general::corba::IdentifierSeq_Transferable transmitRefreshedMeasurementObjects(
						in general::corba::StorableObjectSeq_Transferable StorableObjects_Transferable,
						in configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (general::corba::AMFICOMRemoteException); 

	};
};
};
};
};
};




#endif
