/*-
 * $Id: commonclient.idl,v 1.4 2005/10/22 17:47:25 bass Exp $
 *
 * Copyright ¿ 2004 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */
 
#ifndef COMMONCLIENT_IDL
#define	COMMONCLIENT_IDL

#include "event.idl"
#include "leserver.idl"
 
#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
module com {
module syrus {
module AMFICOM {
#else // MY_COMPILER_IS_NOT_BRAINDEAD
#pragma prefix "AMFICOM.syrus.com"
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

module general {
	module corba {
 

///////////////////////// Client interface //////////////////////////

		/**
		 * Interface for all clients.
		 *
		 * \u002a\u002f@SuppressWarnings("all")/*
		 */
		interface CORBAClient : Verifiable, eventv2::corba::MessageReceiver, leserver::corba::MessageReceiverExt {
		};
	};
};


#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
};
};
};
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

#endif // COMMONCLIENT_IDL
