/*
 * $Id: configuration-vt.idl,v 1.2 2004/12/06 09:55:20 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Научно-технический центр.
 * Проект: АМФИКОМ.
 */

#ifndef CONFIGURATION_VT_IDL
#define CONFIGURATION_VT_IDL

#include "general-vt.idl"

module com {
	module syrus {
		module AMFICOM {
			module configuration {
				module corba {

					abstract valuetype DomainMember {
						attribute general::corba::Identifier domainId;
					};

				};
			};
		};
	};
};
#endif // CONFIGURATION_VT_IDL
