/*-
 * $Id: configuration.idl,v 1.98 2005/07/04 11:33:30 bass Exp $
 *
 * Copyright ¿ 2004-2005 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef CONFIGURATION_IDL
#define CONFIGURATION_IDL

#include "administration.idl"

#pragma prefix "AMFICOM.syrus.com"

module configuration {
	module corba {

// Generic interface to Equipment, MonitoredElement, etc
//	abstract interface MonitoredDomainMember_Transferable {
//		attribute ::general::corba::IdentifierSeq monitored_element_ids;
//
//		void getKIS() raises (::general::corba::AMFICOMRemoteException);
//	};


/////////////////////// EquipmentType /////////////////////
		valuetype IdlEquipmentType: ::general::corba::StorableObject {
			public ::general::corba::WString32 codename;
			public ::general::corba::WString256 description;
			public ::general::corba::WString128 name;
			public ::general::corba::WString128 manufacturer;
			public ::general::corba::WString32 manufacturerCode;

			public ::general::corba::IdentifierSeq characteristicIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::WString32 codename,
					in ::general::corba::WString256 description,
					in ::general::corba::WString128 name,
					in ::general::corba::WString128 manufacturer,
					in ::general::corba::WString32 manufacturerCode,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlEquipmentType EquipmentType;
		typedef sequence<EquipmentType> EquipmentTypeSeq;

/////////////////////// TransmissionPathType /////////////////////
		valuetype IdlTransmissionPathType: ::general::corba::StorableObject {
			public ::general::corba::WString32 codename;
			public ::general::corba::WString256 description;
			public ::general::corba::WString128 name;

			public ::general::corba::IdentifierSeq characteristicIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::WString32 codename,
					in ::general::corba::WString256 description,
					in ::general::corba::WString128 name,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlTransmissionPathType TransmissionPathType;
		typedef sequence<TransmissionPathType> TransmissionPathTypeSeq;

/////////////////////// PortType /////////////////////
		valuetype IdlPortType: ::general::corba::StorableObject {
			enum PortTypeSort {
				PORTTYPESORT_OPTICAL,
				PORTTYPESORT_ELECTRICAL,
				PORTTYPESORT_THERMAL
			};

			enum PortTypeKind {
				PORT_KIND_SIMPLE,
				PORT_KIND_CABLE
			};

			public ::general::corba::WString32 codename;
			public ::general::corba::WString256 description;
			public ::general::corba::WString128 name;
			public PortTypeSort sort;
			public PortTypeKind kind;
			public ::general::corba::IdentifierSeq characteristicIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::WString32 codename,
					in ::general::corba::WString256 description,
					in ::general::corba::WString128 name,
					in PortTypeSort sort,
					in PortTypeKind kind,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlPortType PortType;
		typedef sequence<PortType> PortTypeSeq;

		valuetype IdlMeasurementPortType: ::general::corba::StorableObject {
			public ::general::corba::WString32 codename;
			public ::general::corba::WString256 description;
			public ::general::corba::WString128 name;

			public ::general::corba::IdentifierSeq characteristicIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::WString32 codename,
					in ::general::corba::WString256 description,
					in ::general::corba::WString128 name,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlMeasurementPortType MeasurementPortType;
		typedef sequence<MeasurementPortType> MeasurementPortTypeSeq;

/////////////////////// LinkType /////////////////////
		valuetype IdlAbstractLinkType: ::general::corba::StorableObject {
			enum LinkTypeSort {
				LINKTYPESORT_OPTICAL_FIBER,
				LINKTYPESORT_ETHERNET,
				LINKTYPESORT_GSM
			};

			public ::general::corba::WString32 codename;
			public ::general::corba::WString256 description;
			public ::general::corba::WString128 name;
			public LinkTypeSort sort;
			public ::general::corba::WString128 manufacturer;
			public ::general::corba::WString32 manufacturerCode;
			public ::general::corba::Identifier imageId;
			public ::general::corba::IdentifierSeq characteristicIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::WString32 codename,
					in ::general::corba::WString256 description,
					in ::general::corba::WString128 name,
					in LinkTypeSort sort,
					in ::general::corba::WString128 manufacturer,
					in ::general::corba::WString32 manufacturerCode,
					in ::general::corba::Identifier imageId,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlAbstractLinkType AbstractLinkType;
		typedef sequence<AbstractLinkType> AbstractLinkTypeSeq;

		valuetype IdlLinkType: AbstractLinkType {
			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::WString32 codename,
					in ::general::corba::WString256 description,
					in ::general::corba::WString128 name,
					in LinkTypeSort sort,
					in ::general::corba::WString128 manufacturer,
					in ::general::corba::WString32 manufacturerCode,
					in ::general::corba::Identifier imageId,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlLinkType LinkType;
		typedef sequence<LinkType> LinkTypeSeq;

		valuetype IdlCableLinkType: AbstractLinkType {
			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::WString32 codename,
					in ::general::corba::WString256 description,
					in ::general::corba::WString128 name,
					in LinkTypeSort sort,
					in ::general::corba::WString128 manufacturer,
					in ::general::corba::WString32 manufacturerCode,
					in ::general::corba::Identifier imageId,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlCableLinkType CableLinkType;
		typedef sequence<CableLinkType> CableLinkTypeSeq;

		valuetype IdlCableThreadType: ::general::corba::StorableObject {
			public ::general::corba::WString32 codename;
			public ::general::corba::WString256 description;
			public ::general::corba::WString128 name;

			public long color;

			public ::general::corba::Identifier linkTypeId;
			public ::general::corba::Identifier cableLinkTypeId;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::WString32 codename,
					in ::general::corba::WString256 description,
					in ::general::corba::WString128 name,
					in long color,
					in ::general::corba::Identifier linkTypeId,
					in ::general::corba::Identifier cableLinkTypeId);
		};

		typedef IdlCableThreadType CableThreadType;
		typedef sequence<CableThreadType> CableThreadTypeSeq;

///////////////////////// Equipment ///////////////////////
		valuetype IdlEquipment: ::administration::corba::DomainMember {
			public ::general::corba::Identifier _typeId;

			public ::general::corba::WString128 name;
			public ::general::corba::WString256 description;

			public ::general::corba::WString128 supplier;
			public ::general::corba::WString32 supplierCode;

			public float longitude;
			public float latitude;

			public ::general::corba::WString64 hwSerial;
			public ::general::corba::WString64 hwVersion;
			public ::general::corba::WString64 swSerial;
			public ::general::corba::WString64 swVersion;
			public ::general::corba::WString64 inventoryNumber;

			public ::general::corba::Identifier imageId;

			public ::general::corba::IdentifierSeq characteristicIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::Identifier domainId,
					in ::general::corba::Identifier _typeId,
					in ::general::corba::WString128 name,
					in ::general::corba::WString256 description,
					in ::general::corba::WString128 supplier,
					in ::general::corba::WString32 supplierCode,
					in float longitude,
					in float latitude,
					in ::general::corba::WString64 hwSerial,
					in ::general::corba::WString64 hwVersion,
					in ::general::corba::WString64 swSerial,
					in ::general::corba::WString64 swVersion,
					in ::general::corba::WString64 inventoryNumber,
					in ::general::corba::Identifier imageId,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlEquipment Equipment;
		typedef sequence<Equipment> EquipmentSeq;

///////////////////// Transmission Path ///////////////////
		valuetype IdlTransmissionPath: ::administration::corba::DomainMember {
			public ::general::corba::WString128 name;
			public ::general::corba::WString256 description;

			public ::general::corba::Identifier _typeId;
			public ::general::corba::Identifier startPortId;
			public ::general::corba::Identifier finishPortId;

			public ::general::corba::IdentifierSeq characteristicIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::Identifier domainId,
					in ::general::corba::WString128 name,
					in ::general::corba::WString256 description,
					in ::general::corba::Identifier _typeId,
					in ::general::corba::Identifier startPortId,
					in ::general::corba::Identifier finishPortId,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlTransmissionPath TransmissionPath;
		typedef sequence<TransmissionPath> TransmissionPathSeq;

/////////////////////////////// Port ////////////////////////////////

		valuetype IdlPort: ::general::corba::StorableObject {
			public ::general::corba::Identifier _typeId;
			public ::general::corba::WString256 description;
			public ::general::corba::Identifier equipmentId;

			public ::general::corba::IdentifierSeq characteristicIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::Identifier _typeId,
					in ::general::corba::WString256 description,
					in ::general::corba::Identifier equipmentId,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlPort Port;
		typedef sequence<Port> PortSeq;

//////////////////////////////// KIS ////////////////////////////////
		valuetype IdlKIS: ::administration::corba::DomainMember {
			public ::general::corba::WString128 name;
			public ::general::corba::WString256 description;
			public ::general::corba::WString64 hostname;
			public short tcpPort;
			public ::general::corba::Identifier equipmentId;
			public ::general::corba::Identifier mcmId;
			public ::general::corba::IdentifierSeq characteristicIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::Identifier domainId,
					in ::general::corba::WString128 name,
					in ::general::corba::WString256 description,
					in ::general::corba::WString64 hostname,
					in short tcpPort,
					in ::general::corba::Identifier equipmentId,
					in ::general::corba::Identifier mcmId,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlKIS KIS;
		typedef sequence<KIS> KISSeq;

////////////////////////// MeasurementPort ///////////////////////////
		valuetype IdlMeasurementPort: ::general::corba::StorableObject {
			public ::general::corba::Identifier _typeId;
			public ::general::corba::WString128 name;
			public ::general::corba::WString256 description;
			public ::general::corba::Identifier kisId;
			public ::general::corba::Identifier portId;
			public ::general::corba::IdentifierSeq characteristicIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::Identifier _typeId,
					in ::general::corba::WString128 name,
					in ::general::corba::WString256 description,
					in ::general::corba::Identifier kisId,
					in ::general::corba::Identifier portId,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlMeasurementPort MeasurementPort;
		typedef sequence<MeasurementPort> MeasurementPortSeq;

///////////////////// Monitored Element ///////////////////

		valuetype IdlMonitoredElement: ::administration::corba::DomainMember {
			enum MonitoredElementSort {
				MONITOREDELEMENT_SORT_LINK,
				MONITOREDELEMENT_SORT_TRANSMISSION_PATH,
				MONITOREDELEMENT_SORT_EQUIPMENT,
				MONITOREDELEMENT_SORT_PORT,
				MONITOREDELEMENT_SORT_CABLEPORT
			};

			public ::general::corba::WString128 name;
			public ::general::corba::Identifier measurementPortId;
			public MonitoredElementSort sort;
			public ::general::corba::WString64 localAddress;

			public ::general::corba::IdentifierSeq monitoredDomainMemberIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::Identifier domainId,
					in ::general::corba::WString128 name,
					in ::general::corba::Identifier measurementPortId,
					in MonitoredElementSort sort,
					in ::general::corba::WString64 localAddress,
					in ::general::corba::IdentifierSeq monitoredDomainMemberIds);
		};

		typedef IdlMonitoredElement MonitoredElement;
		typedef sequence<MonitoredElement> MonitoredElementSeq;

///////////////////// Link /////////////////////
		valuetype IdlAbstractLink: ::administration::corba::DomainMember {
			public ::general::corba::WString128 name;
			public ::general::corba::WString256 description;
			public ::general::corba::Identifier _typeId;

			public wstring inventoryNo;
			public ::general::corba::WString128 supplier;
			public ::general::corba::WString32 supplierCode;

			public long color;
			public ::general::corba::WString32 mark;
			public ::general::corba::IdentifierSeq characteristicIds;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::Identifier domainId,
					in ::general::corba::WString128 name,
					in ::general::corba::WString256 description,
					in ::general::corba::Identifier _typeId,
					in wstring inventoryNo,
					in ::general::corba::WString128 supplier,
					in ::general::corba::WString32 supplierCode,
					in long color,
					in ::general::corba::WString32 mark,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlAbstractLink AbstractLink;
		typedef sequence<AbstractLink> AbstractLinkSeq;

		valuetype IdlLink: AbstractLink {
			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::Identifier domainId,
					in ::general::corba::WString128 name,
					in ::general::corba::WString256 description,
					in ::general::corba::Identifier _typeId,
					in wstring inventoryNo,
					in ::general::corba::WString128 supplier,
					in ::general::corba::WString32 supplierCode,
					in long color,
					in ::general::corba::WString32 mark,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlLink Link;
		typedef sequence<Link> LinkSeq;

		valuetype IdlCableLink: AbstractLink {
			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::Identifier domainId,
					in ::general::corba::WString128 name,
					in ::general::corba::WString256 description,
					in ::general::corba::Identifier _typeId,
					in wstring inventoryNo,
					in ::general::corba::WString128 supplier,
					in ::general::corba::WString32 supplierCode,
					in long color,
					in ::general::corba::WString32 mark,
					in ::general::corba::IdentifierSeq characteristicIds);
		};

		typedef IdlCableLink CableLink;
		typedef sequence<CableLink> CableLinkSeq;
///////////////////// CableThread /////////////////////
		valuetype IdlCableThread: ::administration::corba::DomainMember {
			public ::general::corba::WString128 name;
			public ::general::corba::WString256 description;
			public ::general::corba::Identifier _typeId;

			factory defaultInit();
			factory init(in ::general::corba::Identifier id,
					in long long created,
					in long long modified,
					in ::general::corba::Identifier creatorId,
					in ::general::corba::Identifier modifierId,
					in long long version,
					in ::general::corba::Identifier domainId,
					in ::general::corba::WString128 name,
					in ::general::corba::WString256 description,
					in ::general::corba::Identifier _typeId);
		};

		typedef IdlCableThread CableThread;
		typedef sequence<CableThread> CableThreadSeq;
	};
};

#endif // CONFIGURATION_IDL
