/*-
 * $Id: dummy.idl,v 1.3 2005/10/07 14:58:58 bass Exp $
 *
 * Copyright ¿ 2004-2005 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef DUMMY_IDL
#define DUMMY_IDL

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
module com {
module syrus {
module AMFICOM {
#else // MY_COMPILER_IS_NOT_BRAINDEAD
#pragma prefix "AMFICOM.syrus.com"
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

module general {
#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
	struct StorableObject {
		boolean foo;
	};
#else // MY_COMPILER_IS_NOT_BRAINDEAD
	native StorableObject;
#endif // MY_COMPILER_IS_NOT_BRAINDEAD
};

module eventv2 {
#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
	struct Event {
		boolean foo;
	};
#else // MY_COMPILER_IS_NOT_BRAINDEAD
	native Event;
#endif // MY_COMPILER_IS_NOT_BRAINDEAD
};

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
};
};
};
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

#endif // DUMMY_IDL
