/*
 * $Id: event.idl,v 1.16 2005/05/20 21:14:47 arseniy Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Научно-технический центр.
 * Проект: АМФИКОМ.
 */

#ifndef EVENT_IDL
#define	EVENT_IDL

#include "administration.idl"
#include "configuration.idl"
#include "measurement.idl"

module com {
module syrus {
module AMFICOM {
module event {
module corba {

/////////////////////// Event ////////////////////////

	struct EventType_Transferable {
		general::corba::StorableObject header;

		general::corba::WString32 codename;
		general::corba::WString256 description;

		general::corba::IdentifierSeq parameter_type_ids;
		general::corba::IdentifierSeq user_ids;
	};

	typedef sequence <EventType_Transferable> EventTypeSeq_Transferable;



	struct EventParameter_Transferable {
		general::corba::Identifier id;
		general::corba::Identifier type_id;
		wstring value;
	};

	struct EventSource_Transferable {
		general::corba::StorableObject header;

		general::corba::Identifier source_entity_id;
	};

	struct Event_Transferable {
		general::corba::StorableObject header;

		general::corba::Identifier type_id;
		general::corba::WString256 description;

		sequence <EventParameter_Transferable> parameters;
		sequence <general::corba::Identifier> event_source_ids;
	};

	enum AlertKind {
		ALERT_KIND_WINDOW,
		ALERT_KIND_EMAIL,
		ALERT_KIND_SMS
	};


/////////////////// EventListener ////////////////////

	abstract interface EventListener {
		void receiveEvent(in Event_Transferable et) raises (general::corba::AMFICOMRemoteException);
	};

};
};
};
};
};

#endif
