/*
 * $Id: ISM.idl,v 1.8 2004/10/06 11:52:15 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Научно-технический центр.
 * Проект: АМФИКОМ.
 */

#ifndef ISM_IDL
#define ISM_IDL

#include <streams.idl>

#include "general.idl"

module com
{
module syrus
{
module AMFICOM
{
module CORBA
{

module ISM
{
	struct KIS_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring _typeId;

		wstring equipmentId;
		wstring mcmId;

		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <KIS_Transferable> KISSeq_Transferable;

	//former AccessPort_Transferable
	struct MeasurementPort_Transferable
	{
		wstring id;
		wstring name;
#ifndef SERVER
		wstring description;
#endif
		wstring _typeId;
		wstring portId;
		wstring kisId;
		wstring localId;
		wstring domainId;

#ifndef SERVER
		long long modified;
#endif

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <MeasurementPort_Transferable> MeasurementPortSeq_Transferable;

	struct TransmissionPath_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
#ifdef SERVER
		wstring KIS_id;
		wstring measurementPortId;
		wstring local_address;
		wstring monitored_element_id;
#endif
		wstring domainId;

		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <TransmissionPath_Transferable> TransmissionPathSeq_Transferable;

	struct MonitoredElement_Transferable
	{
		wstring id;
		wstring elementName;
		wstring elementId;
		wstring elementType;
		wstring measurementPortId;
		wstring localAddress;
		wstring domainId;

		long long modified;
	};
	typedef sequence <MonitoredElement_Transferable> MonitoredElementSeq_Transferable;

};

module ISMDirectory
{
// catalogue
	//FORMER AccessPortType_Transferable
	struct MeasurementPortType_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring accessType;

		long long modified;

		::CORBA::WStringSeq testTypeIds;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <MeasurementPortType_Transferable> MeasurementPortTypeSeq_Transferable;

	struct TransmissionPathType_Transferable
	{
		wstring id;
		wstring name;
		wstring description;

		long long modified;

#ifndef SERVER
		General::CharacteristicSeq_Transferable characteristics;
#endif
	};
	typedef sequence <TransmissionPathType_Transferable> TransmissionPathTypeSeq_Transferable;

	struct KISType_Transferable
	{
		wstring id;
		wstring name;
		wstring description;

		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <KISType_Transferable> KISTypeSeq_Transferable;
};
};
};
};
};

#endif
