#ifndef _ism_idl_
#define _ism_idl_

#include "general.idl"

module com
{
module syrus
{
module AMFICOM
{
module CORBA
{

module ISM
{
	struct KIS_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring type_id;

		wstring equipment_id;
		wstring mcm_id;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <KIS_Transferable> KISSeq_Transferable;

	//former AccessPort_Transferable
	struct MeasurementPort_Transferable
	{
		wstring id;
		wstring name;
		wstring type_id;
		wstring port_id;
		wstring kis_id;
		wstring local_id;
		wstring domain_id;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <MeasurementPort_Transferable> MeasurementPortSeq_Transferable;

	struct TransmissionPath_Transferable
	{
		wstring id;
		wstring name;
		wstring domain_id;

		long long modified;
	};
	typedef sequence <TransmissionPath_Transferable> TransmissionPathSeq_Transferable;

	struct MonitoredElement_Transferable
	{
		wstring id;
		wstring element_name;
		wstring element_id;
		wstring element_type;
		wstring measurement_port_id;
		wstring local_address;
		wstring domain_id;

		long long modified;
	};
	typedef sequence <MonitoredElement_Transferable> MonitoredElementSeq_Transferable;

};

module ISMDirectory
{
// catalogue
	//FORMER AccessPortType_Transferable
	struct MeasurementPortType_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring access_type;
		long long modified;

		General::wstringSeq test_type_ids;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <MeasurementPortType_Transferable> MeasurementPortTypeSeq_Transferable;

	struct TransmissionPathType_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <TransmissionPathType_Transferable> TransmissionPathTypeSeq_Transferable;

	struct KISType_Transferable
	{
		wstring id;
		wstring name;
		wstring description;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <KISType_Transferable> KISTypeSeq_Transferable;
};
};
};
};
};

#endif
