/*-
 * $Id: leserver.idl,v 1.13.2.2 2006/06/07 08:42:33 arseniy Exp $
 *
 * Copyright ¿ 2004-2005 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef LOGINSERVER_IDL
#define LOGINSERVER_IDL

#include "administration.idl"
#include "event.idl"

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
module com {
module syrus {
module AMFICOM {
#else // MY_COMPILER_IS_NOT_BRAINDEAD
#pragma prefix "AMFICOM.syrus.com"
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

module leserver {
module corba {

	interface LoginServer : general::corba::Verifiable {

		administration::corba::IdlDomainSeq transmitAvailableDomains()
			raises (general::corba::AMFICOMRemoteException);

		void login(in general::corba::WString32 login,
			in general::corba::WString32 password,
			in general::corba::IdlIdentifier domainId,
			in general::corba::CommonUser commonUser,
			out security::corba::IdlSessionKey sessionKey,
			out general::corba::IdlIdentifier userId)
			raises (general::corba::AMFICOMRemoteException);

		void logout(in security::corba::IdlSessionKey sessionKey)
			raises (general::corba::AMFICOMRemoteException);

		void validateLogin(in security::corba::IdlSessionKey sessionKey,
			out long long loginValidationPeriod)
			raises (general::corba::AMFICOMRemoteException);

		void setPassword(in security::corba::IdlSessionKey sessionKey,
			in general::corba::IdlIdentifier userId,
			in general::corba::WString32 password)
			raises (general::corba::AMFICOMRemoteException);
		
	};

	interface EventServer : general::corba::Verifiable {
		void receiveEvents(in eventv2::corba::IdlEventSeq events);
	};
};
};

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
};
};
};
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

#endif // LOGINSERVER_IDL
