/*-
 * $Id: map.idl,v 1.42 2005/10/16 14:23:39 max Exp $
 *
 * Copyright ¿ 2004-2005 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef MAP_IDL
#define MAP_IDL

#include "administration.idl"

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
module com {
module syrus {
module AMFICOM {
#else // MY_COMPILER_IS_NOT_BRAINDEAD
#pragma prefix "AMFICOM.syrus.com"
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

module map {
	module corba {


/////////////////////// SiteNodeType ////////////////////////
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlSiteNodeType : general::corba::IdlStorableObject {
			/*\u002a\u002f@SuppressWarnings("all")/**/
			enum SiteNodeTypeSort {
				WELL,
	 			PIQUET,
				ATS,
				BUILDING,
				CABLE_INLET,
				TOWER,
				UNBOUND
			};
			
			public SiteNodeTypeSort sort;
			
			public wstring codename;
			public wstring name;
			public wstring description;

			public general::corba::IdlIdentifier imageId;
			public boolean topological;
			
			public general::corba::IdlIdentifier mapLibraryId;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in SiteNodeTypeSort sort,
					in wstring codename,
					in wstring name,
					in wstring description,
					in general::corba::IdlIdentifier imageId,
					in boolean topological,
					in general::corba::IdlIdentifier mapLibrary);
		};


/////////////////////// PhysicalLinkType ////////////////////////

		/**
		 * Physical line type such as tunnel, subway, etc.
		 */
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlPhysicalLinkType : general::corba::IdlStorableObject {
			/*\u002a\u002f@SuppressWarnings("all")/**/
			enum PhysicalLinkTypeSort {
				TUNNEL,
				COLLECTOR,
				INDOOR,
				SUBMARINE,
				OVERHEAD,
				UNBOUND
			};
			
			public PhysicalLinkTypeSort sort;
			
			public wstring codename;
			public wstring name;
			public wstring description;
			
			public boolean topological;
			
			public long dimensionX;
			public long dimensionY;
			
			public general::corba::IdlIdentifier mapLibraryId;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in PhysicalLinkTypeSort sort,
					in wstring codename,
					in wstring name,
					in wstring description,
					in long dimensionX,
					in long dimensionY,
					in boolean topological,
					in general::corba::IdlIdentifier mapLibraryId);
		};


/////////////////////// AbstractNode - SiteNode, TopologicalNode ////////////////////////
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlAbstractNode : general::corba::IdlStorableObject {
			public wstring name;
			public wstring description;

			public double longitude;	// anchor
			public double latitude;		// anchor
		};
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlSiteNode : IdlAbstractNode {
			
			public general::corba::IdlIdentifier imageId;
			public general::corba::IdlIdentifier siteNodeTypeId;

			public wstring city;
			public wstring street;
			public wstring building;
			
			public general::corba::IdlIdentifier attachmentSiteNodeId;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in wstring name,
					in wstring description,
					in double  longitude,
					in double latitude,
					in general::corba::IdlIdentifier imageId,
					in general::corba::IdlIdentifier siteNodeTypeId,
					in wstring city,
					in wstring street,
					in wstring building,
					in general::corba::IdlIdentifier attachmentSiteNodeId);
		};
		
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlTopologicalNode : IdlAbstractNode {
			
			public boolean active;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in wstring name,
					in wstring description,
					in double longitude,
					in double latitude,
					in boolean active);
		};


/////////////////////// NodeLink ////////////////////////

		/**
		 * Map item, line fragment.
		 */
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlNodeLink : general::corba::IdlStorableObject {
			
			public general::corba::IdlIdentifier physicalLinkId;

			public general::corba::IdlIdentifier startNodeId;
			public general::corba::IdlIdentifier endNodeId;

			public double length;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in general::corba::IdlIdentifier physicalLinkId,
					in general::corba::IdlIdentifier startNodeId,
					in general::corba::IdlIdentifier endNodeId,
					in double length);
		};


/////////////////////// Mark ////////////////////////

		/**
		 * Mark which has coordinates and is bound to a subway (MapLink) by distance.
		 */
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlMark : IdlAbstractNode {
			
			public general::corba::IdlIdentifier physicalLinkId;

			public double distance;

			public wstring city;
			public wstring street;
			public wstring building;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in wstring name,
					in wstring description,
					in double  longitude,
					in double latitude,
					in general::corba::IdlIdentifier physicalLinkId,
					in double distance,
					in wstring city,
					in wstring street,
					in wstring building);
		};


/////////////////////// PipeBlock ////////////////////////

		/**
		 * Line item.
		 */
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlPipeBlock : general::corba::IdlStorableObject {

			public long number;

			public long dimensionX;
			public long dimensionY;

			public boolean leftToRight;
			public boolean topToBottom;
			public boolean horizontalVertical;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in long number,
					in long dimensionX,
					in long dimensionY,
					in boolean leftToRight,
					in boolean topToBottom,
					in boolean horizontalVertical);
		};

/////////////////////// PhysicalLink ////////////////////////

		/**
		 * Line item.
		 */
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlPhysicalLink : general::corba::IdlStorableObject {
			public wstring name;
			public wstring description;

			public general::corba::IdlIdentifier physicalLinkTypeId;

			public general::corba::IdlIdentifier startNodeId;
			public general::corba::IdlIdentifier endNodeId;

			public wstring city;
			public wstring street;
			public wstring building;

			public general::corba::IdlIdentifierSeq pipeBlockIds;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in wstring name,
					in wstring description,
					in general::corba::IdlIdentifier physicalLinkTypeId,
					in general::corba::IdlIdentifier startNodeId,
					in general::corba::IdlIdentifier endNodeId,
					in wstring city,
					in wstring street,
					in wstring building,
					in general::corba::IdlIdentifierSeq pipeBlockIds);
		};


/////////////////////// Collector ////////////////////////
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlCollector : general::corba::IdlStorableObject {
			public wstring name;
			public wstring description;

			public general::corba::IdlIdentifierSeq physicalLinkIds;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in wstring name,
					in wstring description,
					in general::corba::IdlIdentifierSeq physicalLinkIds);
		};
		
		
//////////////////////// MapLibrary ////////////////////////
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlMapLibrary : general::corba::IdlStorableObject {
			public wstring name;
			public wstring codename;
			public wstring description;
			
			public general::corba::IdlIdentifier parentMapLibraryId;
			
			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in wstring name,
					in wstring codename,
					in wstring description,
					in general::corba::IdlIdentifier parentMapLibraryId);
		};


/////////////////////// Map ////////////////////////
		/*\u002a\u002f@SuppressWarnings("all")/**/
		valuetype IdlMap : administration::corba::IdlDomainMember {
			public wstring name;
			public wstring description;

			public general::corba::IdlIdentifierSeq siteNodeIds;
			public general::corba::IdlIdentifierSeq topologicalNodeIds;
			public general::corba::IdlIdentifierSeq nodeLinkIds;
			public general::corba::IdlIdentifierSeq physicalLinkIds;
			public general::corba::IdlIdentifierSeq markIds;
			public general::corba::IdlIdentifierSeq collectorIds;
			public general::corba::IdlIdentifierSeq mapIds;
			public general::corba::IdlIdentifierSeq externalNodeIds;
			public general::corba::IdlIdentifierSeq mapLibraryIds;

			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in general::corba::IdlIdentifier domainId,
					in wstring name,
					in wstring description,
					in general::corba::IdlIdentifierSeq siteNodeIds,
					in general::corba::IdlIdentifierSeq topologicalNodeIds,
					in general::corba::IdlIdentifierSeq nodeLinkIds,
					in general::corba::IdlIdentifierSeq physicalLinkIds,
					in general::corba::IdlIdentifierSeq markIds,
					in general::corba::IdlIdentifierSeq collectorIds,
					in general::corba::IdlIdentifierSeq mapIds,
					in general::corba::IdlIdentifierSeq externalNodeIds,
					in general::corba::IdlIdentifierSeq mapLibraryIds);
		};


/////////////////////// /// ////////////////////////
		/*\u002a\u002f@SuppressWarnings("all")/**/
		struct IdlTopologicalImageQuery {
			long mapImageWidth;
			long mapImageHeight;

			double topoCenterX;
			double topoCenterY;
			double topoScale;

			::CORBA::BooleanSeq layerVisibilities;
			::CORBA::BooleanSeq labelVisibilities;
		};
		/*\u002a\u002f@SuppressWarnings("all")/**/
		struct IdlRenderedImage {
			::CORBA::OctetSeq image;
		};
		/*\u002a\u002f@SuppressWarnings("all")/**/
		struct IdlMapFeature {
			double centerX;
			double centerY;

			wstring name;
		};
		/*\u002a\u002f@SuppressWarnings("all")/**/
		typedef sequence<IdlMapFeature> IdlMapFeatureSeq;
		
		/*\u002a\u002f@SuppressWarnings("all")/**/
		struct IdlMapDescriptor {
			wstring name;
			wstring fileName;
			wstring filePathName;
			
			long long length;
			long long lastModified;
		};
		/*\u002a\u002f@SuppressWarnings("all")/**/
		typedef sequence<IdlMapDescriptor> IdlMapDescriptorSeq;
		
		/*\u002a\u002f@SuppressWarnings("all")/**/
		struct IdlLayerDescriptor {
			wstring fileName;
			wstring pathName;
			
			long long length;
			long long lastModified;
		};
		/*\u002a\u002f@SuppressWarnings("all")/**/
		typedef sequence<IdlLayerDescriptor> IdlLayerDescriptorSeq;
	};
};

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
};
};
};
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

#endif // MAP_IDL
