/*-
 * $Id: mapview.idl,v 1.2 2005/07/10 13:49:37 bass Exp $
 *
 * Copyright ¿ 2004-2005 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef MAPVIEW_IDL
#define MAPVIEW_IDL

#include "administration.idl"

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
module com {
module syrus {
module AMFICOM {
#else // MY_COMPILER_IS_NOT_BRAINDEAD
#pragma prefix "AMFICOM.syrus.com"
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

module mapview {
	module corba {
#ifdef NO_ALIASES
		valuetype IdlMapView: administration::corba::IdlDomainMember {
#else // NO_ALIASES
		valuetype IdlMapView: administration::corba::DomainMember {
#endif // NO_ALIASES
			public wstring name;
			public wstring description;

			public double longitude;
			public double latitude;
			public double scale;
			public double defaultScale;

			public general::corba::Identifier mapId;
			public general::corba::IdentifierSeq schemeIds;

#ifndef NO_DEFAULT_FACTORIES
			factory defaultInit();
#endif // NO_DEFAULT_FACTORIES
			factory init(in general::corba::Identifier id,
					in long long created,
					in long long modified,
					in general::corba::Identifier creatorId,
					in general::corba::Identifier modifierId,
					in long long version,
					in general::corba::Identifier domainId,
					in wstring name,
					in wstring description,
					in double longitude,
					in double latitude,
					in double scale,
					in double defaultScale,
					in general::corba::Identifier mapId,
					in general::corba::IdentifierSeq schemeIds);
		};

		typedef IdlMapView MapView;
		typedef sequence<MapView> MapViewSeq;
	};
};

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
};
};
};
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

#endif // MAPVIEW_IDL
