#ifndef MCM_IDL
#define MCM_IDL

#include "measurement.idl"
#include "configuration.idl"

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
module com {
module syrus {
module AMFICOM {
#else // MY_COMPILER_IS_NOT_BRAINDEAD
#pragma prefix "AMFICOM.syrus.com"
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

module mcm {
module corba {

	interface MCM : general::corba::CommonServer {

		void startTests(in general::corba::IdlIdentifierSeq testIds,
					in security::corba::IdlSessionKey sessionKey)
					raises (general::corba::AMFICOMRemoteException);

		void stopTests(in general::corba::IdlIdentifierSeq testIds,
					in security::corba::IdlSessionKey sessionKey)
					raises (general::corba::AMFICOMRemoteException);

	};

};
};

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
};
};
};
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

#endif // MCM_IDL
