#ifndef MSERVER_IDL
#define MSERVER_IDL

#include "general.idl"

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
module com {
module syrus {
module AMFICOM {
#else // MY_COMPILER_IS_NOT_BRAINDEAD
#pragma prefix "AMFICOM.syrus.com"
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

module mserver {
module corba {

	interface MServer : general::corba::CommonServer, general::corba::IdentifierGeneratorServer {
		//Ничего особенного
	};

};
};

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
};
};
};
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

#endif // MSERVER_IDL
