/*-
 * $Id: mshserver.idl,v 1.10 2005/05/20 11:45:18 bass Exp $
 *
 * Copyright ¿ 2004-2005 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef MSHSERVER_IDL
#define MSHSERVER_IDL

#include "map.idl"
#include "scheme.idl"

module com {
	module syrus {
		module AMFICOM {
			module mshserver {
				module corba {
					interface MSHServer:
							general::corba::IdentifierGeneratorServer,
							general::corba::Verifiable {
						void delete(in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);		

/*-************************************************************
 * Map -- receive multiple objects.                           *
 **************************************************************/

						general::corba::StorableObjectSeq receiveSiteNodes(
								in map::corba::SiteNodeSeq siteNodes,
								in boolean force, 	
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveTopologicalNodes(
								in map::corba::TopologicalNodeSeq topologicalNodes,
								in boolean force, 	
							in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveNodeLinks(
								in map::corba::NodeLinkSeq nodeLinks,
								in boolean force, 	
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);	

						general::corba::StorableObjectSeq receiveMarks(
								in map::corba::MarkSeq marks,
								in boolean force, 	
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);	

						general::corba::StorableObjectSeq receivePhysicalLinks(
								in map::corba::PhysicalLinkSeq physicalLinks,
								in boolean force, 	
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);	

						general::corba::StorableObjectSeq receiveCollectors(
								in map::corba::CollectorSeq collectors,
								in boolean force, 	
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);	

						general::corba::StorableObjectSeq receiveMaps(
								in map::corba::MapSeq maps,
								in boolean force, 	
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);	

						general::corba::StorableObjectSeq receiveSiteNodeTypes(
								in map::corba::SiteNodeTypeSeq siteNodeTypes,
								in boolean force, 	
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receivePhysicalLinkTypes(
								in map::corba::PhysicalLinkTypeSeq physicalLinkTypes,
								in boolean force, 	
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

/*-************************************************************
 * Map -- transmit multiple objects.                          *
 **************************************************************/

						map::corba::SiteNodeSeq transmitSiteNodes(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						map::corba::TopologicalNodeSeq transmitTopologicalNodes(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						map::corba::NodeLinkSeq transmitNodeLinks(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);	

						map::corba::MarkSeq transmitMarks(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);	

						map::corba::PhysicalLinkSeq transmitPhysicalLinks(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);	

						map::corba::CollectorSeq transmitCollectors(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);	

						map::corba::MapSeq transmitMaps(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);	

						map::corba::SiteNodeTypeSeq transmitSiteNodeTypes(
								in general::corba::IdentifierSeq ids,	
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						map::corba::PhysicalLinkTypeSeq transmitPhysicalLinkTypes(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

/*-************************************************************
 * Scheme -- receive multiple objects.                        *
 **************************************************************/

						general::corba::StorableObjectSeq receiveSchemeProtoGroups(
								in scheme::corba::SchemeProtoGroupSeq schemeProtoGroups,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemeProtoElements(
								in scheme::corba::SchemeProtoElementSeq schemeProtoElements,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemes(
								in scheme::corba::SchemeSeq schemes,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemeElements(
								in scheme::corba::SchemeElementSeq schemeElements,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemeOptimizeInfos(
								in scheme::corba::SchemeOptimizeInfoSeq schemeOptimizeInfos,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemeOptimizeInfoSwitches(
								in scheme::corba::SchemeOptimizeInfoSwitchSeq schemeOptimizeInfoSwitches,
								in boolean force,
								in security::corba::SessionKey sessionKey)
						  raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemeOptimizeInfoRtus(
								in scheme::corba::SchemeOptimizeInfoRtuSeq schemeOptimizeInfoRtus,
								in boolean force,
								in security::corba::SessionKey sessionKey)
						  raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemeMonitoringSolutions(
								in scheme::corba::SchemeMonitoringSolutionSeq schemeMonitoringSolutions,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemeDevices(
								in scheme::corba::SchemeDeviceSeq schemeDevices,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemePorts(
								in scheme::corba::SchemePortSeq schemePorts,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemeCablePorts(
								in scheme::corba::SchemeCablePortSeq schemeCablePorts,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemeLinks(
								in scheme::corba::SchemeLinkSeq schemeLinks,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemeCableLinks(
								in scheme::corba::SchemeCableLinkSeq schemeCableLinks,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemeCableThreads(
								in scheme::corba::SchemeCableThreadSeq schemeCableThreads,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveCableChannelingItems(
								in scheme::corba::CableChannelingItemSeq cableChannelingItems,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receiveSchemePaths(
								in scheme::corba::SchemePathSeq schemePaths,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						general::corba::StorableObjectSeq receivePathElements(
								in scheme::corba::PathElementSeq pathElements,
								in boolean force, 
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

/*-************************************************************
 * Scheme -- transmit multiple objects.                       *
 **************************************************************/

						scheme::corba::SchemeProtoGroupSeq transmitSchemeProtoGroups(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeProtoElementSeq transmitSchemeProtoElements(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeSeq transmitSchemes(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeElementSeq transmitSchemeElements(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeOptimizeInfoSeq transmitSchemeOptimizeInfos(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeOptimizeInfoSwitchSeq transmitSchemeOptimizeInfoSwitches(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeOptimizeInfoRtuSeq transmitSchemeOptimizeInfoRtus(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeMonitoringSolutionSeq transmitSchemeMonitoringSolutions(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeDeviceSeq transmitSchemeDevices(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemePortSeq transmitSchemePorts(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeCablePortSeq transmitSchemeCablePorts(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeLinkSeq transmitSchemeLinks(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeCableLinkSeq transmitSchemeCableLinks(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemeCableThreadSeq transmitSchemeCableThreads(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::CableChannelingItemSeq transmitCableChannelingItems(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::SchemePathSeq transmitSchemePaths(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);

						scheme::corba::PathElementSeq transmitPathElements(
								in general::corba::IdentifierSeq ids,
								in security::corba::SessionKey sessionKey)
								raises (general::corba::AMFICOMRemoteException);
					};
				};
			};
		};
	};
};

#endif // MSHSERVER_IDL
