#ifndef _network_idl_
#define _network_idl_

#include "general.idl"

module com
{
module syrus
{
module AMFICOM
{
module CORBA
{

module Network
{
	struct Port_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring _typeId;
		wstring interfaceId;
		wstring addressId;
		wstring localId;
		wstring equipmentId;
		wstring domainId;
		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <Port_Transferable> PortSeq_Transferable;

	struct CablePort_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring _typeId;
		wstring interfaceId;
		wstring addressId;
		wstring localId;
		wstring equipmentId;
		wstring domainId;
		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <CablePort_Transferable> CablePortSeq_Transferable;

	struct Equipment_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring _typeId;

		wstring longitude;
		wstring latitude;

		wstring hwSerial;
		wstring swSerial;
		wstring hwVersion;
		wstring swVersion;
		wstring inventoryNr;
		wstring manufacturer;
		wstring manufacturerCode;
		wstring supplier;
		wstring supplierCode;

		wstring eqClass;

		wstring domainId;

		wstring imageId;

		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <Equipment_Transferable> EquipmentSeq_Transferable;

	struct Link_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring _typeId;

		wstring inventoryNr;
		wstring manufacturer;
		wstring manufacturerCode;
		wstring supplier;
		wstring supplierCode;

		wstring domainId;

		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <Link_Transferable> LinkSeq_Transferable;

	struct CableLinkThread_Transferable
	{
		wstring id;
		wstring name;
		wstring color;
		wstring mark;
		wstring linkTypeId;
	};
	typedef sequence <CableLinkThread_Transferable> CableLinkThreadSeq_Transferable;

	struct CableLink_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring _typeId;

		wstring inventoryNr;
		wstring manufacturer;
		wstring manufacturerCode;
		wstring supplier;
		wstring supplierCode;

		wstring imageId;

		wstring domainId;

		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <CableLink_Transferable> CableLinkSeq_Transferable;
};

module NetworkDirectory
{
	struct EquipmentType_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring manufacturer;
		wstring manufacturerCode;
		wstring eqClass;

		wstring imageId;
		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <EquipmentType_Transferable> EquipmentTypeSeq_Transferable;

	struct PortType_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring interfaceId;
		wstring pClass;

		wstring imageId;
		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <PortType_Transferable> PortTypeSeq_Transferable;

	struct CablePortType_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring interfaceId;
		wstring pClass;

		wstring imageId;
		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <CablePortType_Transferable> CablePortTypeSeq_Transferable;

	struct LinkType_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring linkClass;
		wstring manufacturer;
		wstring manufacturerCode;

		wstring imageId;
		long long modified;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <LinkType_Transferable> LinkTypeSeq_Transferable;

	struct CableTypeThread_Transferable
	{
		wstring id;
		wstring name;
		wstring color;
		wstring mark;
		wstring linkTypeId;
	};
	typedef sequence <CableTypeThread_Transferable> CableTypeThreadSeq_Transferable;

	struct CableLinkType_Transferable
	{
		wstring id;
		wstring name;
		wstring description;
		wstring linkClass;
		wstring manufacturer;
		wstring manufacturerCode;

		wstring imageId;
		long long modified;

		CableTypeThreadSeq_Transferable cableThreads;

		General::CharacteristicSeq_Transferable characteristics;
	};
	typedef sequence <CableLinkType_Transferable> CableLinkTypeSeq_Transferable;
};
};
};
};
};

#endif
