/*-
 * $Id: report.idl,v 1.10 2005/11/16 18:13:08 max Exp $
 *
 * Copyright © 2004-${year} Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef REPORT_IDL
#define REPORT_IDL

#include "general.idl"

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
module com {
module syrus {
module AMFICOM {
#else // MY_COMPILER_IS_NOT_BRAINDEAD
#pragma prefix "AMFICOM.syrus.com"
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

module report {
	module corba {
		
		/////////////////////// AbstractReportElement ////////////////////////
		valuetype IdlAbstractReportElement : general::corba::IdlStorableObject {
			public long locationX;
			public long locationY;
			public long width;
			public long height;
			public general::corba::IdlIdentifier idlReportTemplateId;
		};
		
		/////////////////////// AttachedText extends AbstractReportElement ///
		valuetype IdlAttachedText : IdlAbstractReportElement {
			
			struct IdlFont {
				general::corba::WString64 name;
				long style;
				long size;
			};
			
			public wstring text;
			public general::corba::IdlIdentifier verticalAttacherId;
			public general::corba::IdlIdentifier horizontalAttacherId;
			
			public long distanceX;
			public long distanceY;
			
			public IdlFont font;
			
			public long verticalAttachType;
			public long horizontalAttachType;
									
			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in long locationX,
					in long locationY,
					in long width,
					in long height,
					in general::corba::IdlIdentifier idlReportTemplateId,
					in wstring text,
					in general::corba::IdlIdentifier verticalAttacherId,
					in general::corba::IdlIdentifier horizontalAttacherId,
					in long distanceX,
					in long distanceY,
					in IdlFont font,
					in long verticalAttachType,
					in long horizontalAttachType);
		};
		
		/////////////////////// Image extends AbstractReportElement ///
		valuetype IdlImage : IdlAbstractReportElement {
			public general::corba::IdlIdentifier bitmapImageResource;
			
			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in long locationX,
					in long locationY,
					in long width,
					in long height,
					in general::corba::IdlIdentifier idlReportTemplateId,
					in general::corba::IdlIdentifier bitmapImageResource);
		
		};
		
		/////////////////////// AbstractData extends AbstractElement /
		
		valuetype IdlAbstractData : IdlAbstractReportElement {
			public general::corba::WString128 reportName;
			public general::corba::WString128 modelClassName;
		};
		
		/////////////////////// Data extends AbstractData ////////////
		valuetype IdlData : IdlAbstractData {		
			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in long locationX,
					in long locationY,
					in long width,
					in long height,
					in general::corba::IdlIdentifier idlReportTemplateId,
					in general::corba::WString128 reportName,
					in general::corba::WString128 modelClassName);
		};
		
		/////////////////////// TableData extends AbstractData ///////////////
		valuetype IdlTableData : IdlAbstractData {
			public long verticalDivisionCount;
			
			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in long locationX,
					in long locationY,
					in long width,
					in long height,
					in general::corba::IdlIdentifier idlReportTemplateId,
					in general::corba::WString128 reportName,
					in general::corba::WString128 modelClassName,
					in long verticalDivisionCount);
		};
		
		/////////////////////// ReportTemplate ///////////////
		valuetype IdlReportTemplate : general::corba::IdlStorableObject {
			
			enum IdlOrientation {
					PORTRAIT,
					LANDSCAPE};
			
			enum IdlSheetSize {
					A0,
					A1,
					A2,
					A3,
					A4};
			
			public general::corba::WString32 name;
			public general::corba::WString256 description;
			
			public IdlSheetSize sheetSize;
			
			public IdlOrientation idlOrientation;
						
			public long marginSize;
			public general::corba::WString64 destinationModule;
			
			factory init(in general::corba::IdlIdentifier id,
					in long long created,
					in long long modified,
					in general::corba::IdlIdentifier creatorId,
					in general::corba::IdlIdentifier modifierId,
					in long long version,
					in general::corba::WString32 name,
					in general::corba::WString256 description,
					in IdlSheetSize sheetSize,
					in IdlOrientation idlOrientation,
					in long marginSize,
					in general::corba::WString64 destinationModule);		
		};
				
	};
};

#ifndef MY_COMPILER_IS_NOT_BRAINDEAD
};
};
};
#endif // MY_COMPILER_IS_NOT_BRAINDEAD

#endif // REPORT_IDL
