#ifndef _report_idl_
#define _report_idl_

#include <general.idl>

module com
{
module syrus
{
module AMFICOM
{
module CORBA
{

module Report
{
	struct RenderingObject_Transferable
	{
		wstring roID;
		long objectX;
		long objectY;
		long width;
		long height;
		sequence <octet> incapsulated_report;
		sequence <long> column_widths;
		long tableDivisionsNumber;
	};

	struct FirmedTextPane_Transferable
	{
		long labelX;
		long labelY;
		wstring strings_contained;
		wstring labels_font;

		wstring vertFirmer;
		wstring horizFirmer;
		wstring verticalFirmTo;
		wstring horizontalFirmTo;
		long distanceX;
		long distanceY;
	};

	struct ImagePane_Transferable
	{
		long x;
		long y;
		long width;
		long height;
		
		General::octetSeq bytes;
	};

	struct ReportTemplate_Transferable
	{
		wstring id;
		wstring name;
		long long modified;
		wstring description;
		wstring template_type;

		//объекты
		sequence <RenderingObject_Transferable> renderingObjects;

		//надписи
		sequence <FirmedTextPane_Transferable> firmedTextPanes;

		//картинки
//		sequence <ImagePane_Transferable> imagePanes;

		//фильтры
		//sequence <ObjectResourceFilter_Transferable> objectResourceFilters;
	};
	typedef sequence <ReportTemplate_Transferable> ReportTemplateSeq_Transferable;

};
};
};
};
};

#endif
