/*
 * $Id: resource.idl,v 1.10 2004/12/15 09:42:49 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef RESOURCE_IDL
#define RESOURCE_IDL

#include <streams.idl>

#include "general.idl"

module com {
	module syrus {
		module AMFICOM {
			module resource {
				module corba {
					union ImageResourceData switch (enum ImageResourceSort {
							BITMAP,
							FILE,
							SCHEME}) {
						case BITMAP:
							struct BitmapImageResourceData {
								general::corba::WString32 codename;
								::CORBA::OctetSeq image;
							} bitmapImageResourceData;
						case FILE:
							general::corba::WString256 fileName;
						case SCHEME:
							::CORBA::OctetSeq image;
					};

					/**
					 * @todo Once migration to valuetypes is
					 *       complete, move enum and union
					 *       inside.
					 */
					struct ImageResource_Transferable {
						general::corba::StorableObject_Transferable header;
						ImageResourceData data;
					};

					typedef sequence<ImageResource_Transferable> ImageResourceSeq_Transferable;
					typedef ImageResource_Transferable ImageResource;
					typedef sequence<ImageResource> ImageResourceSeq;
				};
			};

			module CORBA {
				module Resource {
					/**
					 * @deprecated Use {@link com.syrus.AMFICOM.resource.corba.ImageResource_Transferable} instead.
					 */
					struct ImageResource_Transferable {
						wstring id;
						wstring name;
						wstring source_string;

						wstring filename;		// only one of these
						::CORBA::OctetSeq image;	// should be valid
					};
					typedef sequence<ImageResource_Transferable> ImageResourceSeq_Transferable;

					struct ResourceDescriptor_Transferable {
						wstring resource_id;
						long long resource_modified;
					};

					typedef sequence<ResourceDescriptor_Transferable> ResourceDescriptorSeq_Transferable;

				   	struct Filter_Transferable {
						wstring id;
						wstring resource_typ;
						::CORBA::OctetSeq logic_scheme;
					};

					typedef sequence<Filter_Transferable> FilterSeq_Transferable;
				};
			};
		};
	};
};

#endif // RESOURCE_IDL
