/*-
 * $Id: resource.idl,v 1.16 2005/06/24 09:40:48 bass Exp $
 *
 * Copyright ¿ 2004 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef RESOURCE_IDL
#define RESOURCE_IDL

#include "general.idl"

module com {
	module syrus {
		module AMFICOM {
			module resource {
				module corba {
					typedef struct IdlImageResource {
						general::corba::StorableObject header;
						union ImageResourceData switch (enum ImageResourceSort {
								BITMAP,
								FILE,
								SCHEME}) {
							case BITMAP:
								struct BitmapImageResourceData {
									general::corba::WString32 codename;
									::CORBA::OctetSeq image;
								} bitmapImageResourceData;
							case FILE:
								general::corba::WString256 fileName;
							case SCHEME:
								::CORBA::OctetSeq image;
						} data;
					} ImageResource;

					typedef sequence<ImageResource> ImageResourceSeq;
				};
			};
		};
	};
};

#endif // RESOURCE_IDL
