/*
 * $Id: scheme-configuration.idl,v 1.5 2004/12/22 10:02:43 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef SCHEME_CONFIGURATION_IDL
#define SCHEME_CONFIGURATION_IDL

#include "configuration.idl"

module com {
	module syrus {
		module AMFICOM {
			module configuration {
				native AbstractLinkType;
				native CableLinkType;
				native CableThreadType;
				native Characteristic;
				native Domain;
				native Equipment;
				native EquipmentType;
				native KIS;
				native Link;
				native LinkType;
				native MeasurementPort;
				native MeasurementPortType;
				native Port;
				native PortType;
				native TransmissionPath;
				native TransmissionPathType;
				native User;

				abstract valuetype Characterizable {
					void addCharacteristic(in Characteristic characteristic);
					void removeCharacteristic(in Characteristic characteristic);
				};

				abstract valuetype ComSyrusAmficomConfigurationAbstractSchemePort {
					attribute configuration::corba::PortType portType;
					attribute PortType portTypeImpl;
					attribute configuration::corba::Port port;
					attribute Port portImpl;
					attribute configuration::corba::MeasurementPortType measurementPortType;
					attribute MeasurementPortType measurementPortTypeImpl;
					attribute configuration::corba::MeasurementPort measurementPort;
					attribute MeasurementPort measurementPortImpl;
				};

				abstract valuetype ComSyrusAmficomConfigurationAbstractSchemeLink {
					attribute configuration::corba::AbstractLinkType abstractLinkType;
					attribute AbstractLinkType abstractLinkTypeImpl;
					attribute configuration::corba::Link link;
					attribute Link linkImpl;
				};

				abstract valuetype ComSyrusAmficomConfigurationSchemeLink {
					/**
					 * @see com.syrus.AMFICOM.scheme.corba.AbstractSchemeLink#abstractLinkTypeId
					 */
					attribute configuration::corba::LinkType linkType;
					attribute LinkType linkTypeImpl;
				};

				abstract valuetype ComSyrusAmficomConfigurationSchemeCableThread {
					attribute configuration::corba::CableThreadType cableThreadType;
					attribute CableThreadType cableThreadTypeImpl;
					attribute configuration::corba::Link thread;
					attribute Link threadImpl;
				};

				abstract valuetype ComSyrusAmficomConfigurationSchemeCableLink {
					/**
					 * @see com.syrus.AMFICOM.scheme.corba.AbstractSchemeLink#abstractLinkTypeId
					 */
					attribute configuration::corba::CableLinkType cableLinkType;
					attribute CableLinkType cableLinkTypeImpl;
				};

				abstract valuetype ComSyrusAmficomConfigurationSchemePath {
					attribute configuration::corba::TransmissionPathType type;
					attribute TransmissionPathType typeImpl;
					attribute configuration::corba::TransmissionPath path;
					attribute TransmissionPath pathImpl;
				};

				abstract valuetype ComSyrusAmficomConfigurationSchemeProtoElement {
					attribute configuration::corba::EquipmentType equipmentType;
					attribute EquipmentType equipmentTypeImpl;
				};

				abstract valuetype ComSyrusAmficomConfigurationSchemeElement {
					attribute configuration::corba::EquipmentType equipmentType;
					attribute EquipmentType equipmentTypeImpl;
					attribute configuration::corba::Equipment equipment;
					attribute Equipment equipmentImpl;
					attribute configuration::corba::Rtu rtu;
					attribute KIS rtuImpl;
				};

				abstract valuetype ComSyrusAmficomConfigurationScheme {
					/**
					 * @see com.syrus.AMFICOM.scheme.corba.Scheme#domainId
					 */
					attribute configuration::corba::Domain domain;
					attribute Domain domainImpl;
				};
			};
		};
	};
};

#endif // SCHEME_CONFIGURATION_IDL
