/*
 * $Id: scheme-resource.idl,v 1.2 2004/12/06 08:30:36 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Dept. of Science & Technology.
 * Project: AMFICOM.
 */

#ifndef SCHEME_RESOURCE_IDL
#define SCHEME_RESOURCE_IDL

#include "resource.idl"

module com {
	module syrus {
		module AMFICOM {
			module resource {
				native BitmapImageResource;
				native SchemeImageResource;

				abstract valuetype SchemeSymbolContainer {
					attribute corba::ImageResource symbol;
					attribute BitmapImageResource symbolImpl;
				};

				abstract valuetype SchemeCellContainer: SchemeSymbolContainer {
					attribute corba::ImageResource schemeCell;
					attribute SchemeImageResource schemeCellImpl;
					attribute corba::ImageResource ugoCell;
					attribute SchemeImageResource ugoCellImpl;
				};
			};
		};
	};
};

#endif // SCHEME_RESOURCE_IDL
