/*
 * $Id: streams.idl,v 1.2 2005/06/24 17:57:46 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Научно-технический центр.
 * Проект: АМФИКОМ.
 */

#ifndef STREAMS_IDL
#define STREAMS_IDL

#pragma prefix "omg.org"

/**
 * @author $Author: bass $
 * @version $Revision: 1.2 $, $Date: 2005/06/24 17:57:46 $
 * @module idl_v1
 */
module CORBA {
	typedef sequence<any> AnySeq;
	typedef sequence<boolean> BooleanSeq;
	typedef sequence<char> CharSeq;
	typedef sequence<double> DoubleSeq;
	typedef sequence<float> FloatSeq;
	typedef sequence<long long> LongLongSeq;
	typedef sequence<long> LongSeq;
	typedef sequence<octet> OctetSeq;
	typedef sequence<short> ShortSeq;
	typedef sequence<string> StringSeq;
	typedef sequence<unsigned long long> ULongLongSeq;
	typedef sequence<unsigned long> ULongSeq;
	typedef sequence<unsigned short> UShortSeq;
	typedef sequence<wchar> WCharSeq;
	typedef sequence<wstring> WStringSeq;
};

#endif // STREAMS_IDL
