#!/bin/bash


JAVA=$JAVA_HOME/bin/java
LIB=$HOME/lib
ORACLECLASSPATH=$ORACLE_HOME/jdbc/lib/ojdbc14_g.jar:$ORACLE_HOME/jdbc/lib/orai18n.jar:$ORACLE_HOME/jdbc/lib/classes12.jar:$ORACLE_HOME/jdbc/lib/nls_charset12.jar
APPCLASSPATH=$LIB/mserver_interface.jar:\
$LIB/cmserver.jar:\
$LIB/measurement.jar:\
$LIB/configuration.jar:\
$LIB/administration.jar:\
$LIB/general.jar:\
$LIB/event.jar:\
$LIB/util.jar

$JAVA -Xloggc:./gc -Xmx256m -server -ea -classpath $APPCLASSPATH:$ORACLECLASSPATH com.syrus.AMFICOM.cmserver.ClientMeasurementServer &
# Expands to the process ID of the most recently executed background (asynchronous) command.
echo $! > pid
