#!/bin/bash


JAVA=$JAVA_HOME/bin/java
LIB=../lib
ORACLECLASSPATH=$ORACLE_HOME/jdbc/lib/ojdbc14_g.jar:$ORACLE_HOME/jdbc/lib/orai18n.jar
APPCLASSPATH=$LIB/mserver_interface.jar:\
$LIB/mcm_interface.jar:\
$LIB/cmserver.jar:\
$LIB/cmserver_interface.jar:\
$LIB/measurement.jar:\
$LIB/configuration.jar:\
$LIB/general.jar:\
$LIB/event.jar:\
$LIB/util.jar

exec $JAVA -server -classpath $APPCLASSPATH:$ORACLECLASSPATH com.syrus.AMFICOM.cmserver.ClientMeasurementServer
