@@domain.sql
@@server.sql
@@mcm.sql
@@equipment.sql
@@port.sql
@@transmissionpath.sql
@@characteristic.sql
@@kis.sql
@@measurementport.sql
@@monitoredelement.sql
@@equipmentmelink.sql
@@transmissionpathmelink.sql
@@link.sql
