CREATE TABLE KIS (
 id VARCHAR2(32),
 mcm_id VARCHAR2(32) NOT NULL,
--
 CONSTRAINT kis_pk PRIMARY KEY (id),
 CONSTRAINT kis_mcm_fk FOREIGN KEY (mcm_id)
  REFERENCES MCM (id) ON DELETE CASCADE
);

CREATE SEQUENCE kis_seq ORDER;

