CREATE DATABASE mongol
 USER sys IDENTIFIED BY sys
 USER system IDENTIFIED BY manager
 MAXDATAFILES 70
 MAXINSTANCES 1
 CHARACTER SET AL32UTF8
 NATIONAL CHARACTER SET AL16UTF16
 LOGFILE
   GROUP 1 ('/u01/oradata/mongol/redo01.log') SIZE 100M,
   GROUP 2 ('/u11/oradata/mongol/redo11.log') SIZE 100M
  MAXLOGFILES 4
  MAXLOGMEMBERS 4
 EXTENT MANAGEMENT LOCAL
  DATAFILE '/u01/oradata/mongol/system01.dbf' SIZE 300M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 500M
  SYSAUX DATAFILE '/u01/oradata/mongol/sysaux01.dbf' SIZE 300M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 500M
  DEFAULT TABLESPACE users
   DATAFILE '/u01/oradata/mongol/users01.dbf' SIZE 500M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 1000M
   EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  DEFAULT TEMPORARY TABLESPACE temp
   TEMPFILE '/u01/oradata/mongol/temp01.dbf' SIZE 10M REUSE AUTOEXTEND ON NEXT 1M MAXSIZE 100M
   EXTENT MANAGEMENT LOCAL
  UNDO TABLESPACE undotbs
   DATAFILE '/u01/oradata/mongol/undotbs01.dbf' SIZE 200M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
 SET TIME_ZONE = 'Europe/Moscow';
