#!/bin/bash


JAVA=$JAVA_HOME/bin/java
LIB=../lib
TRANSCEIVER=./transceiver
ORACLECLASSPATH=$ORACLE_HOME/jdbc/lib/ojdbc14_g.jar:$ORACLE_HOME/jdbc/lib/orai18n.jar
APPCLASSPATH=$LIB/mcm.jar:$LIB/mserver_interface.jar:$LIB/measurement.jar:$LIB/configuration.jar:$LIB/event.jar:$LIB/general.jar:$LIB/util.jar

exec $JAVA -server -Djava.library.path=$TRANSCEIVER -classpath $APPCLASSPATH:$ORACLECLASSPATH com.syrus.AMFICOM.mcm.MeasurementControlModule
