#!/bin/bash


JAVA=$JAVA_HOME/bin/java
LIB=../lib
ORACLECLASSPATH=$ORACLE_HOME/jdbc/lib/classes12.jar
APPCLASSPATH=$LIB/mcm.jar:$LIB/mserver_interface.jar:$LIB/measurement.jar:$LIB/configuration.jar:$LIB/general.jar:$LIB/util.jar

exec $JAVA -server -classpath $APPCLASSPATH:$ORACLECLASSPATH com.syrus.AMFICOM.mcm.MeasurementControlModule -setup
