#!/bin/bash


JAVA=$JAVA_HOME/bin/java
LIB=../lib
EXTLIB=../../extlib

EXTCLASSPATH=$EXTLIB/kunststoff.jar:$EXTLIB/trove.jar:$EXTLIB/jdev-rt.jar
#ORACLECLASSPATH=$ORACLE_HOME/jdbc/lib/ojdbc14_g.jar:$ORACLE_HOME/jdbc/lib/orai18n.jar:$ORACLE_HOME/jdbc/lib/classes12.jar:$ORACLE_HOME/jdbc/lib/nls_charset12.jar
APPCLASSPATH=$LIB/scheduler.jar:\
$LIB/general.jar:\
$LIB/administration.jar:\
$LIB/configuration.jar:\
$LIB/measurement.jar:\
$LIB/map.jar:\
$LIB/mapview.jar:\
$LIB/scheme.jar:\
$LIB/filter.jar:\
$LIB/resource.jar:\
$LIB/csbridge.jar:\
$LIB/commonclient.jar:\
$LIB/filterclient.jar:\
$LIB/cmserver_interface.jar:\
$LIB/util.jar

$JAVA -Xmx256m -client -ea -classpath $APPCLASSPATH:$EXTCLASSPATH com.syrus.AMFICOM.Client.Schedule.Schedule

