#!/bin/bash

LIB=../lib
TRANSCEIVER=./transceiver
DADARA=./dadara:$ROOTSYS/lib
ORBCLASSPATH=$ORACLE_HOME/lib/aurora_client.jar:$ORACLE_HOME/lib/vbjorb.jar:$ORACLE_HOME/lib/vbjapp.jar
APPCLASSPATH=$LIB/agent.jar:$LIB/kisserver.jar:$LIB/corba.jar:$LIB/util.jar
JAVA=java

$JAVA -Djava.library.path=$TRANSCEIVER:$DADARA -classpath $APPCLASSPATH:$ORBCLASSPATH com.syrus.AMFICOM.agent.Agent
