package com.syrus.AMFICOM.resource;


/**
* com/syrus/AMFICOM/resource/SchemeSymbolContainer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-resource.idl
* 4 Март 2005 г. 18:11:10 MSK
*/

public interface SchemeSymbolContainer
{
  public abstract com.syrus.AMFICOM.resource.corba.ImageResource_Transferable symbol ();

  public abstract void symbol (com.syrus.AMFICOM.resource.corba.ImageResource_Transferable newSymbol);

  public abstract BitmapImageResource symbolImpl ();

  public abstract void symbolImpl (BitmapImageResource newSymbolImpl);

} // interface SchemeSymbolContainer
