package com.syrus.AMFICOM.resource;


/**
* com/syrus/AMFICOM/resource/SchemeCellContainer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-resource.idl
* 4 Март 2005 г. 18:11:10 MSK
*/

public interface SchemeCellContainer extends com.syrus.AMFICOM.resource.SchemeSymbolContainer
{
  public abstract com.syrus.AMFICOM.resource.corba.ImageResource_Transferable schemeCell ();

  public abstract void schemeCell (com.syrus.AMFICOM.resource.corba.ImageResource_Transferable newSchemeCell);

  public abstract SchemeImageResource schemeCellImpl ();

  public abstract void schemeCellImpl (SchemeImageResource newSchemeCellImpl);

  public abstract com.syrus.AMFICOM.resource.corba.ImageResource_Transferable ugoCell ();

  public abstract void ugoCell (com.syrus.AMFICOM.resource.corba.ImageResource_Transferable newUgoCell);

  public abstract SchemeImageResource ugoCellImpl ();

  public abstract void ugoCellImpl (SchemeImageResource newUgoCellImpl);

} // interface SchemeCellContainer
