#ifndef _MSERVER_IDL_
#define _MSERVER_IDL_

#include <general.idl>
#include <measurement.idl>
#include <configuration.idl>

module com {
module syrus {
module AMFICOM {
module mserver {
module corba {

	interface MServer : com::syrus::AMFICOM::general::corba::IdentifierGeneratorServer {

		void transmitTests(in com::syrus::AMFICOM::measurement::corba::TestSeq_Transferable tests) raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		void ping(in long i) raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
	};

};
};
};
};
};

#endif
