#ifndef _MSERVER_IDL_
#define _MSERVER_IDL_

#include <general.idl>
#include <measurement.idl>
#include <configuration.idl>

module com {
module syrus {
module AMFICOM {
module mserver {
module corba {

	interface MServer : com::syrus::AMFICOM::general::corba::IdentifierGeneratorServer {

////////////////////////////////////////////	Receive ///////////////////////////////////////////////////
		void receiveResults(in com::syrus::AMFICOM::measurement::corba::ResultSeq_Transferable results,
												in com::syrus::AMFICOM::general::corba::Identifier_Transferable mcm_id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);


/////////////////////////////////////////	Configuration ////////////////////////////////////////////////
		com::syrus::AMFICOM::configuration::corba::CharacteristicType_Transferable transmitCharacteristicType(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::EquipmentType_Transferable transmitEquipmentType(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::PortType_Transferable transmitPortType(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::MeasurementPortType_Transferable transmitMeasurementPortType(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::Characteristic_Transferable transmitCharacteristic(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::User_Transferable transmitUser(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::Domain_Transferable transmitDomain(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::Server_Transferable transmitServer(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::MCM_Transferable transmitMCM(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::Equipment_Transferable transmitEquipment(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::Port_Transferable transmitPort(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::TransmissionPath_Transferable transmitTransmissionPath(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::KIS_Transferable transmitKIS(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::MeasurementPort_Transferable transmitMeasurementPort(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::MonitoredElement_Transferable transmitMonitoredElement(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);


		com::syrus::AMFICOM::configuration::corba::MonitoredElementSeq_Transferable transmitKISMonitoredElements(in com::syrus::AMFICOM::general::corba::Identifier_Transferable kis_id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);


/////////////////////////////////////////	Measurement //////////////////////////////////////////////////
		com::syrus::AMFICOM::measurement::corba::Analysis_Transferable transmitAnalysis(
				in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
				raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		com::syrus::AMFICOM::measurement::corba::AnalysisSeq_Transferable transmitAnalyses(
				in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable id)
				raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
				
		com::syrus::AMFICOM::measurement::corba::AnalysisSeq_Transferable transmitAnalysesButIds(
				in com::syrus::AMFICOM::configuration::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable,
				in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable id_Transfearbles)
				raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
				
		com::syrus::AMFICOM::measurement::corba::Evaluation_Transferable transmitEvaluation(
				in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
				raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
				
		com::syrus::AMFICOM::measurement::corba::MeasurementSeq_Transferable transmitMeasurements(
				in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable id)
				raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
				
		com::syrus::AMFICOM::measurement::corba::MeasurementSeq_Transferable transmitMeasurementsButIds(
				in com::syrus::AMFICOM::configuration::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable,
				in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable id)
				raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		com::syrus::AMFICOM::measurement::corba::EvaluationSeq_Transferable transmitEvaluations(
				in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable id)
				raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
				
		com::syrus::AMFICOM::measurement::corba::EvaluationSeq_Transferable transmitEvaluationsButIds(
				in com::syrus::AMFICOM::configuration::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable,
				in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable id)
				raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		com::syrus::AMFICOM::measurement::corba::ParameterType_Transferable transmitParameterType(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::MeasurementType_Transferable transmitMeasurementType(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::AnalysisType_Transferable transmitAnalysisType(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::EvaluationType_Transferable transmitEvaluationType(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::Set_Transferable transmitSet(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::MeasurementSetup_Transferable transmitMeasurementSetup(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::Test_Transferable transmitTest(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::TemporalPattern_Transferable transmitTemporalPattern(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);


		void updateTestStatus(in com::syrus::AMFICOM::general::corba::Identifier_Transferable id, in com::syrus::AMFICOM::measurement::corba::TestStatus status);


//////////////////////////////////////////////////////////////////////////////////////////////////////
		void ping(in long i)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
	};

};
};
};
};
};

#endif
