package com.syrus.AMFICOM.scheme.corba.SchemePackage;


/**
* com/syrus/AMFICOM/scheme/corba/SchemePackage/Type.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public class Type implements org.omg.CORBA.portable.IDLEntity {
	private static final long serialVersionUID = 3616726075988784953L;
private        int __value;
  private static int __size = 8;
  private static com.syrus.AMFICOM.scheme.corba.SchemePackage.Type[] __array = new com.syrus.AMFICOM.scheme.corba.SchemePackage.Type [__size];

  public static final int _BUILDING = 0;
  public static final com.syrus.AMFICOM.scheme.corba.SchemePackage.Type BUILDING = new com.syrus.AMFICOM.scheme.corba.SchemePackage.Type(_BUILDING);
  public static final int _CABLE_SUBNETWORK = 1;
  public static final com.syrus.AMFICOM.scheme.corba.SchemePackage.Type CABLE_SUBNETWORK = new com.syrus.AMFICOM.scheme.corba.SchemePackage.Type(_CABLE_SUBNETWORK);
  public static final int _NETWORK = 2;
  public static final com.syrus.AMFICOM.scheme.corba.SchemePackage.Type NETWORK = new com.syrus.AMFICOM.scheme.corba.SchemePackage.Type(_NETWORK);
  public static final int _FLOOR = 3;
  public static final com.syrus.AMFICOM.scheme.corba.SchemePackage.Type FLOOR = new com.syrus.AMFICOM.scheme.corba.SchemePackage.Type(_FLOOR);
  public static final int _ROOM = 4;
  public static final com.syrus.AMFICOM.scheme.corba.SchemePackage.Type ROOM = new com.syrus.AMFICOM.scheme.corba.SchemePackage.Type(_ROOM);
  public static final int _RACK = 5;
  public static final com.syrus.AMFICOM.scheme.corba.SchemePackage.Type RACK = new com.syrus.AMFICOM.scheme.corba.SchemePackage.Type(_RACK);
  public static final int _BAY = 6;
  public static final com.syrus.AMFICOM.scheme.corba.SchemePackage.Type BAY = new com.syrus.AMFICOM.scheme.corba.SchemePackage.Type(_BAY);
  public static final int _CARDCAGE = 7;
  public static final com.syrus.AMFICOM.scheme.corba.SchemePackage.Type CARDCAGE = new com.syrus.AMFICOM.scheme.corba.SchemePackage.Type(_CARDCAGE);

  public int value ()
  {
    return this.__value;
  }

  public static com.syrus.AMFICOM.scheme.corba.SchemePackage.Type from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Type (int value)
  {
    this.__value = value;
    __array[this.__value] = this;
  }
} // class Type
