package com.syrus.AMFICOM.general.corba;


/**
* com/syrus/AMFICOM/general/corba/Describable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/general-vt.idl
* 4 Март 2005 г. 18:07:48 MSK
*/

public interface Describable
{
  public abstract String description ();

  public abstract void description (String newDescription);

} // interface Describable
