package com.syrus.AMFICOM.general.corba;


/**
* com/syrus/AMFICOM/general/corba/IStorableObject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/general-vt.idl
* 4 Март 2005 г. 18:07:48 MSK
*/

public interface IStorableObject extends com.syrus.AMFICOM.general.Identifiable
{
  public abstract long getCreated ();

  public abstract long getModified ();

  public abstract com.syrus.AMFICOM.general.Identifier getCreatorId ();

  public abstract com.syrus.AMFICOM.general.Identifier getModifierId ();

  public abstract long getVersion ();

  public abstract boolean isChanged ();

  public abstract void setChanged (StorableObjectFactory invoker, boolean changed);

  public abstract com.syrus.AMFICOM.general.corba.StorableObject_Transferable getHeaderTransferable ();


  /**
  						 * Since dependencies may include both valuetyped and non-valuetyped storable
  						 * objects, they are returned as a sequence of valuetyped identifiers, as
  						 * valutyped and non-valuetyped ones can be easily converted into each other.
  						 */
  public abstract com.syrus.AMFICOM.general.Identifier[] getDependencies ();

} // interface IStorableObject
