package com.syrus.AMFICOM.general.corba;


/**
* com/syrus/AMFICOM/general/corba/StorableObject.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/general-vt.idl
* 4 Март 2005 г. 18:07:48 MSK
*/

public abstract class StorableObject implements com.syrus.AMFICOM.general.corba.IStorableObject
{
  protected com.syrus.AMFICOM.general.Identifier id = null;
  protected long created = 0;
  protected long modified = 0;
  protected com.syrus.AMFICOM.general.Identifier creatorId = null;
  protected com.syrus.AMFICOM.general.Identifier modifierId = null;
  protected long version = 0;

  public abstract com.syrus.AMFICOM.general.corba.StorableObject cloneInstance ();

  public abstract void setAttributes (long created, long modified, com.syrus.AMFICOM.general.Identifier creatorId, com.syrus.AMFICOM.general.Identifier modifierId, long version);
} // class StorableObject
