/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syrus_AMFICOM_analysis_dadara_ModelFunction */

#ifndef _Included_com_syrus_AMFICOM_analysis_dadara_ModelFunction
#define _Included_com_syrus_AMFICOM_analysis_dadara_ModelFunction
#ifdef __cplusplus
extern "C" {
#endif
#undef com_syrus_AMFICOM_analysis_dadara_ModelFunction_FITMODE_VARY_ALL
#define com_syrus_AMFICOM_analysis_dadara_ModelFunction_FITMODE_VARY_ALL 1L
#undef com_syrus_AMFICOM_analysis_dadara_ModelFunction_FITMODE_VARY_LIN
#define com_syrus_AMFICOM_analysis_dadara_ModelFunction_FITMODE_VARY_LIN 2L
#undef com_syrus_AMFICOM_analysis_dadara_ModelFunction_FITMODE_SET_LINEAR
#define com_syrus_AMFICOM_analysis_dadara_ModelFunction_FITMODE_SET_LINEAR 3L
#undef com_syrus_AMFICOM_analysis_dadara_ModelFunction_FITMODE_SET_BREAKL
#define com_syrus_AMFICOM_analysis_dadara_ModelFunction_FITMODE_SET_BREAKL 4L
#undef com_syrus_AMFICOM_analysis_dadara_ModelFunction_FITMODE_SET_SMOOTH
#define com_syrus_AMFICOM_analysis_dadara_ModelFunction_FITMODE_SET_SMOOTH 5L
#undef com_syrus_AMFICOM_analysis_dadara_ModelFunction_LINK_FIXLEFT
#define com_syrus_AMFICOM_analysis_dadara_ModelFunction_LINK_FIXLEFT 1L
/*
 * Class:     com_syrus_AMFICOM_analysis_dadara_ModelFunction
 * Method:    nF
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_syrus_AMFICOM_analysis_dadara_ModelFunction_nF
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_syrus_AMFICOM_analysis_dadara_ModelFunction
 * Method:    nFArray
 * Signature: (DDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_syrus_AMFICOM_analysis_dadara_ModelFunction_nFArray
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     com_syrus_AMFICOM_analysis_dadara_ModelFunction
 * Method:    nChangeByACXL
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_com_syrus_AMFICOM_analysis_dadara_ModelFunction_nChangeByACXL
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_syrus_AMFICOM_analysis_dadara_ModelFunction
 * Method:    nRMS
 * Signature: ([DII)D
 */
JNIEXPORT jdouble JNICALL Java_com_syrus_AMFICOM_analysis_dadara_ModelFunction_nRMS
  (JNIEnv *, jobject, jdoubleArray, jint, jint);

/*
 * Class:     com_syrus_AMFICOM_analysis_dadara_ModelFunction
 * Method:    nFit
 * Signature: ([DIIIIDDIID)V
 */
JNIEXPORT void JNICALL Java_com_syrus_AMFICOM_analysis_dadara_ModelFunction_nFit
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jint, jint, jdouble, jdouble, jint, jint, jdouble);

/*
 * Class:     com_syrus_AMFICOM_analysis_dadara_ModelFunction
 * Method:    nGetAttr
 * Signature: (Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_com_syrus_AMFICOM_analysis_dadara_ModelFunction_nGetAttr
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_syrus_AMFICOM_analysis_dadara_ModelFunction
 * Method:    nInitAsLinear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_syrus_AMFICOM_analysis_dadara_ModelFunction_nInitAsLinear
  (JNIEnv *, jobject);

/*
 * Class:     com_syrus_AMFICOM_analysis_dadara_ModelFunction
 * Method:    nSetAsLinear
 * Signature: (IDID)V
 */
JNIEXPORT void JNICALL Java_com_syrus_AMFICOM_analysis_dadara_ModelFunction_nSetAsLinear
  (JNIEnv *, jobject, jint, jdouble, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
