/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syrus_AMFICOM_analysis_CoreAnalysisManager */

#ifndef _Included_com_syrus_AMFICOM_analysis_CoreAnalysisManager
#define _Included_com_syrus_AMFICOM_analysis_CoreAnalysisManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syrus_AMFICOM_analysis_CoreAnalysisManager
 * Method:    gauss
 * Signature: ([DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_syrus_AMFICOM_analysis_CoreAnalysisManager_gauss
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdouble);

/*
 * Class:     com_syrus_AMFICOM_analysis_CoreAnalysisManager
 * Method:    analyse2
 * Signature: (I[DDDDDDDD[DII)[Lcom/syrus/AMFICOM/analysis/dadara/ReflectogramEvent;
 */
JNIEXPORT jobjectArray JNICALL Java_com_syrus_AMFICOM_analysis_CoreAnalysisManager_analyse2
  (JNIEnv *, jclass, jint, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray, jint, jint);

/*
 * Class:     com_syrus_AMFICOM_analysis_CoreAnalysisManager
 * Method:    nCalcNoise3s
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_com_syrus_AMFICOM_analysis_CoreAnalysisManager_nCalcNoise3s
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
