include ../Makefile.inc

OBJS= \
        ModelF.$(OBJ_EXT) \
	dadara-init.$(OBJ_EXT) \
        EPold2EPnew.$(OBJ_EXT) \
        EventParams.$(OBJ_EXT) \
        Java-bridge.$(OBJ_EXT) \
        mat-solve.$(OBJ_EXT) \
        MathRef.$(OBJ_EXT) \
        prf-MSVC-rdtsc.$(OBJ_EXT)
#        prf-gen.$(OBJ_EXT)

include ../Makefile.all
