package com.syrus.AMFICOM.administration;


/**
* com/syrus/AMFICOM/administration/ComSyrusAmficomAdministrationScheme.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-administration.idl
* 4 Март 2005 г. 18:11:04 MSK
*/

public interface ComSyrusAmficomAdministrationScheme
{

  /**
  					 * @see com.syrus.AMFICOM.scheme.corba.Scheme#domainId
  					 */
  public abstract com.syrus.AMFICOM.administration.corba.Domain_Transferable domain ();


  /**
  					 * @see com.syrus.AMFICOM.scheme.corba.Scheme#domainId
  					 */
  public abstract void domain (com.syrus.AMFICOM.administration.corba.Domain_Transferable newDomain);

  public abstract Domain domainImpl ();

  public abstract void domainImpl (Domain newDomainImpl);

} // interface ComSyrusAmficomAdministrationScheme
