#ifndef _CMSERVER_IDL_
#define _CMSERVER_IDL_

#include <general.idl>
#include <measurement.idl>
#include <configuration.idl>

module com {
module syrus {
module AMFICOM {
module cmserver {
module corba {

	interface CMServer : com::syrus::AMFICOM::general::corba::IdentifierGeneratorServer {
//////////////////////////////////////////// Measurement Receive //////////////////////////////////////////////
		void receiveAnalysis(in com::syrus::AMFICOM::measurement::corba::Analysis_Transferable analysis_Transferable,
								  in boolean force, 	
						 		  in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		void receiveAnalyses(in com::syrus::AMFICOM::measurement::corba::AnalysisSeq_Transferable sets,
								  in boolean force, 	
						 		  in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveAnalysisType(in com::syrus::AMFICOM::measurement::corba::AnalysisType_Transferable analysisType_Transferable,
								  in boolean force, 	
						 		  in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		void receiveAnalysisTypes(in com::syrus::AMFICOM::measurement::corba::AnalysisTypeSeq_Transferable sets,
								  in boolean force, 	
						 		  in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		void receiveEvaluation(in com::syrus::AMFICOM::measurement::corba::Evaluation_Transferable evaluation_Transferable,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveEvaluations(in com::syrus::AMFICOM::measurement::corba::EvaluationSeq_Transferable sets,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		void receiveEvaluationType(in com::syrus::AMFICOM::measurement::corba::EvaluationType_Transferable evaluationType_Transferable,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveEvaluationTypes(in com::syrus::AMFICOM::measurement::corba::EvaluationTypeSeq_Transferable sets,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveMeasurement(in com::syrus::AMFICOM::measurement::corba::Measurement_Transferable measurement_Transferable,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveMeasurements(in com::syrus::AMFICOM::measurement::corba::MeasurementSeq_Transferable sets,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		void receiveMeasurementSetup(in com::syrus::AMFICOM::measurement::corba::MeasurementSetup_Transferable measurementSetup_Transferable,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveMeasurementSetups(in com::syrus::AMFICOM::measurement::corba::MeasurementSetupSeq_Transferable sets,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveMeasurementType(in com::syrus::AMFICOM::measurement::corba::MeasurementType_Transferable measurementType_Transferable,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveMeasurementTypes(in com::syrus::AMFICOM::measurement::corba::MeasurementTypeSeq_Transferable sets,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveModeling(in com::syrus::AMFICOM::measurement::corba::Modeling_Transferable modeling_Transferable,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveModelings(in com::syrus::AMFICOM::measurement::corba::ModelingSeq_Transferable sets,
									in boolean force,
						 		  	in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
				
		void receiveParameterType(in com::syrus::AMFICOM::measurement::corba::ParameterType_Transferable parameterType_Transferable,
								   in boolean force,
						 		   in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveParameterTypes(in com::syrus::AMFICOM::measurement::corba::ParameterTypeSeq_Transferable sets,
								   in boolean force,
						 		   in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		void receiveResult(in com::syrus::AMFICOM::measurement::corba::Result_Transferable result_Transferable,
								   in boolean force,
						 		   in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveResults(in com::syrus::AMFICOM::measurement::corba::ResultSeq_Transferable sets,
								   in boolean force,
						 		   in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		void receiveSet(in com::syrus::AMFICOM::measurement::corba::Set_Transferable set_Transferable,
						 in boolean force,
						 in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		void receiveSets(in com::syrus::AMFICOM::measurement::corba::SetSeq_Transferable sets,
						 in boolean force,
						 in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
				
		void receiveTemporalPattern(in com::syrus::AMFICOM::measurement::corba::TemporalPattern_Transferable temporalPattern_Transferable,
								   in boolean force,
						 		   in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		void receiveTemporalPatterns(in com::syrus::AMFICOM::measurement::corba::TemporalPatternSeq_Transferable sets,
								   in boolean force,
						 		   in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		void receiveTest(in com::syrus::AMFICOM::measurement::corba::Test_Transferable test_Transferable,
						  in boolean force,
						  in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);	
		
		void receiveTests(in com::syrus::AMFICOM::measurement::corba::TestSeq_Transferable tests,
						  in boolean force,
						  in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);	
						
///////////////////////////////////////// Configuration Transmit ///////////////////////////////////////////////
		com::syrus::AMFICOM::configuration::corba::Domain_Transferable transmitDomain(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);	\
			
		com::syrus::AMFICOM::configuration::corba::MonitoredElement_Transferable transmitMonitoredElement(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);	
			
		
		com::syrus::AMFICOM::configuration::corba::TransmissionPath_Transferable transmitTransmissionPath(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

					// Transmit Sequences		

		com::syrus::AMFICOM::configuration::corba::DomainSeq_Transferable transmitDomains(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::configuration::corba::MonitoredElementSeq_Transferable transmitMonitoredElements(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::configuration::corba::TransmissionPathSeq_Transferable transmitTransmissionPaths(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
	
///////////////////////////////////////// Measurement Transmit ///////////////////////////////////////////////

		
					// Transmit one object
					
		com::syrus::AMFICOM::measurement::corba::AnalysisType_Transferable transmitAnalysisType(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);			
			
		com::syrus::AMFICOM::measurement::corba::EvaluationType_Transferable transmitEvaluationType(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::MeasurementType_Transferable transmitMeasurementType(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);			

		com::syrus::AMFICOM::measurement::corba::ParameterType_Transferable transmitParameterType(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);	

		com::syrus::AMFICOM::measurement::corba::Analysis_Transferable transmitAnalysis(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::Evaluation_Transferable transmitEvaluation(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
						
		com::syrus::AMFICOM::measurement::corba::Modeling_Transferable transmitModeling(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		com::syrus::AMFICOM::measurement::corba::Measurement_Transferable transmitMeasurement(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);		

		com::syrus::AMFICOM::measurement::corba::MeasurementSetup_Transferable transmitMeasurementSetup(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);						

		com::syrus::AMFICOM::measurement::corba::Result_Transferable transmitResult(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);				

		com::syrus::AMFICOM::measurement::corba::Set_Transferable transmitSet(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);				
		
		com::syrus::AMFICOM::measurement::corba::TemporalPattern_Transferable transmitTemporalPattern(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::Test_Transferable transmitTest(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);					
					
					// Transmit Sequences		

		com::syrus::AMFICOM::measurement::corba::AnalysisTypeSeq_Transferable transmitAnalysisTypes(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::AnalysisTypeSeq_Transferable transmitAnalysisTypesButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)			
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
					
		com::syrus::AMFICOM::measurement::corba::EvaluationTypeSeq_Transferable transmitEvaluationTypes(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::EvaluationTypeSeq_Transferable transmitEvaluationTypesButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);						

		com::syrus::AMFICOM::measurement::corba::MeasurementTypeSeq_Transferable transmitMeasurementTypes(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::MeasurementTypeSeq_Transferable transmitMeasurementTypesButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::ParameterTypeSeq_Transferable transmitParameterTypes(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::ParameterTypeSeq_Transferable transmitParameterTypesButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::ParameterTypeSeq_Transferable transmitParameterTypesButIdsCondition(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier,
			in com::syrus::AMFICOM::measurement::corba::StringFieldCondition_Transferable stringFieldCondition_Transferable)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::AnalysisSeq_Transferable transmitAnalyses(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::AnalysisSeq_Transferable transmitAnalysesButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::AnalysisSeq_Transferable transmitAnalysesButIdsCondition(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier,
			in com::syrus::AMFICOM::configuration::corba::DomainCondition_Transferable domainCondition)			
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::EvaluationSeq_Transferable transmitEvaluations(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::EvaluationSeq_Transferable transmitEvaluationsButIdsCondition(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier,
			in com::syrus::AMFICOM::configuration::corba::DomainCondition_Transferable domainCondition)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::EvaluationSeq_Transferable transmitEvaluationsButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		com::syrus::AMFICOM::measurement::corba::ModelingSeq_Transferable transmitModelings(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::ModelingSeq_Transferable transmitModelingsButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::ModelingSeq_Transferable transmitModelingsButIdsCondition(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier,
			in com::syrus::AMFICOM::configuration::corba::DomainCondition_Transferable domainCondition)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::MeasurementSeq_Transferable transmitMeasurements(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::MeasurementSeq_Transferable transmitMeasurementsButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::MeasurementSeq_Transferable transmitMeasurementsButIdsCondition(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier,
			in com::syrus::AMFICOM::measurement::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable)			
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::MeasurementSetupSeq_Transferable transmitMeasurementSetups(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::MeasurementSetupSeq_Transferable transmitMeasurementSetupsButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::MeasurementSetupSeq_Transferable transmitMeasurementSetupsButIdsCondition(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier,
			in com::syrus::AMFICOM::measurement::corba::MeasurementSetupCondition_Transferable measurementSetupCondition_Transferable)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);			
				
		com::syrus::AMFICOM::measurement::corba::ResultSeq_Transferable transmitResults(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::ResultSeq_Transferable transmitResultsButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::ResultSeq_Transferable transmitResultsButIdsCondition(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier,
			in com::syrus::AMFICOM::measurement::corba::LinkedIdsCondition_Transferable linkedIdsCondition_Transferable)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
				
		com::syrus::AMFICOM::measurement::corba::SetSeq_Transferable transmitSets(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::SetSeq_Transferable transmitSetsButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::SetSeq_Transferable transmitSetsButIdsCondition(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier,
			in com::syrus::AMFICOM::configuration::corba::DomainCondition_Transferable domainCondition)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

		com::syrus::AMFICOM::measurement::corba::TemporalPatternSeq_Transferable transmitTemporalPatterns(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::TemporalPatternSeq_Transferable transmitTemporalPatternsButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);						
			
		com::syrus::AMFICOM::measurement::corba::TestSeq_Transferable transmitTests(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::TestSeq_Transferable transmitTestsButIds(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		com::syrus::AMFICOM::measurement::corba::TestSeq_Transferable transmitTestsButIdsCondition(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids,
			in com::syrus::AMFICOM::configuration::corba::AccessIdentifier_Transferable accessIdentifier,
			in com::syrus::AMFICOM::measurement::corba::TestCondition_Transferable testCondition)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);	
		
				
		
	};
};
};
};
};
};




#endif
