#ifndef _CMSERVER_IDL_
#define _CMSERVER_IDL_

#include <general.idl>
#include <measurement.idl>
#include <configuration.idl>

module com {
module syrus {
module AMFICOM {
module cmserver {
module corba {

	interface CMServer : com::syrus::AMFICOM::general::corba::IdentifierGeneratorServer {
//////////////////////////////////////////// Measurement Receive //////////////////////////////////////////////
		void receiveTests(in com::syrus::AMFICOM::measurement::corba::TestSeq_Transferable tests)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		void receiveSets(in com::syrus::AMFICOM::measurement::corba::SetSeq_Transferable tests)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);

///////////////////////////////////////// Measurement Transmit ///////////////////////////////////////////////

		
					// Transmit one object
					
		com::syrus::AMFICOM::measurement::corba::AnalysisType_Transferable transmitAnalysisType(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);			
			
		com::syrus::AMFICOM::measurement::corba::EvaluationType_Transferable transmitEvaluationType(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::MeasurementSetup_Transferable transmitMeasurementSetup(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
						
		com::syrus::AMFICOM::measurement::corba::MeasurementType_Transferable transmitMeasurementType(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);			

		com::syrus::AMFICOM::measurement::corba::ParameterType_Transferable transmitParameterType(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);			

		com::syrus::AMFICOM::measurement::corba::Set_Transferable transmitSet(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);				
			
		com::syrus::AMFICOM::measurement::corba::Test_Transferable transmitTest(
			in com::syrus::AMFICOM::general::corba::Identifier_Transferable id)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);					
					
					// Transmit Sequences		

		com::syrus::AMFICOM::measurement::corba::AnalysisTypeSeq_Transferable transmitAnalysisTypes(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::EvaluationTypeSeq_Transferable transmitEvaluationTypes(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);						

		com::syrus::AMFICOM::measurement::corba::MeasurementSetupSeq_Transferable transmitMeasurementSetups(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
		
		com::syrus::AMFICOM::measurement::corba::MeasurementTypeSeq_Transferable transmitMeasurementTypes(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::SetSeq_Transferable transmitSets(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);
			
		com::syrus::AMFICOM::measurement::corba::TestSeq_Transferable transmitTests(
			in com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable ids)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);		
					
		com::syrus::AMFICOM::measurement::corba::TestSeq_Transferable transmitTestsByTime(
			in long long startTime, in long long endTime)
			raises (com::syrus::AMFICOM::general::corba::AMFICOMRemoteException);		

		
			
		
	};
};
};
};
};
};




#endif
