package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/AbstractSchemePortPackage/AbstractSchemePortDirectionType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public class AbstractSchemePortDirectionType implements org.omg.CORBA.portable.IDLEntity
{
	private static final long serialVersionUID = 3979273525527917364L;
private        int __value;
  private static int __size = 2;
  private static com.syrus.AMFICOM.scheme.corba.AbstractSchemePortDirectionType[] __array = new com.syrus.AMFICOM.scheme.corba.AbstractSchemePortDirectionType [__size];

  public static final int __IN = 0;
  public static final com.syrus.AMFICOM.scheme.corba.AbstractSchemePortDirectionType _IN = new com.syrus.AMFICOM.scheme.corba.AbstractSchemePortDirectionType(__IN);
  public static final int __OUT = 1;
  public static final com.syrus.AMFICOM.scheme.corba.AbstractSchemePortDirectionType _OUT = new com.syrus.AMFICOM.scheme.corba.AbstractSchemePortDirectionType(__OUT);

  public int value ()
  {
    return this.__value;
  }

	public static com.syrus.AMFICOM.scheme.corba.AbstractSchemePortDirectionType from_int(
			int value) {
		if (value >= 0 && value < __size)
			return __array[value];
		throw new org.omg.CORBA.BAD_PARAM();
	}

  protected AbstractSchemePortDirectionType (int value)
  {
    this.__value = value;
    __array[this.__value] = this;
  }
} // class AbstractSchemePortDirectionType
