package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/AbstractSchemeElement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class AbstractSchemeElement implements com.syrus.AMFICOM.general.corba.IStorableObject, com.syrus.AMFICOM.general.corba.Namable, com.syrus.AMFICOM.general.corba.Describable, com.syrus.AMFICOM.general.Characterizable
{
  protected String thisName = null;
  protected String thisDescription = null;
  protected com.syrus.AMFICOM.general.Identifier schemeId = null;
  protected com.syrus.AMFICOM.general.Identifier characteristicIds[] = null;


  /**
  						 * Getter returns scheme parent to this scheme link or scheme cable link or scheme element.
  						 * @see #schemeId
  						 */
  public abstract com.syrus.AMFICOM.scheme.corba.Scheme scheme ();


  /**
  						 * Getter returns scheme parent to this scheme link or scheme cable link or scheme element.
  						 * @see #schemeId
  						 */
  public abstract void scheme (com.syrus.AMFICOM.scheme.corba.Scheme newScheme);


  /**
  						 * Transient attribute
  						 */
  public abstract boolean alarmed ();


  /**
  						 * Transient attribute
  						 */
  public abstract void alarmed (boolean newAlarmed);
} // class AbstractSchemeElement
