package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/AbstractSchemeLink.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class AbstractSchemeLink extends com.syrus.AMFICOM.scheme.corba.AbstractSchemeElement implements com.syrus.AMFICOM.configuration.ComSyrusAmficomConfigurationAbstractSchemeLink
{

 /**
 						 * Depending on implementation, may reference either {@link SchemePort} or {@link SchemeCablePort}.
 						 */
  protected com.syrus.AMFICOM.general.Identifier sourceAbstractSchemePortId = null;

 /**
 						 * Depending on implementation, may reference either {@link SchemePort} or {@link SchemeCablePort}.
 						 */
  protected com.syrus.AMFICOM.general.Identifier targetAbstractSchemePortId = null;

 /**
 						 * Depending on implementation, may reference either {@link com.syrus.AMFICOM.configuration.LinkType} or {@link com.syrus.AMFICOM.configuration.CableLinkType}.
 						 */
  protected com.syrus.AMFICOM.general.Identifier abstractLinkTypeId = null;

 /**
 						 * Depending on implementation, may reference either {@link com.syrus.AMFICOM.configuration.Link link} or {@link com.syrus.AMFICOM.configuration.Link cable link}.
 						 */
  protected com.syrus.AMFICOM.general.Identifier linkId = null;

 /**
 						 * 0 means either zero or unspecified length.
 						 *
 						 * @see #physicalLength()
 						 */
  protected double thisPhysicalLength = (double)0;

 /**
 						 * 0 means either zero or unspecified length.
 						 *
 						 * @see #opticalLength()
 						 */
  protected double thisOpticalLength = (double)0;

  public abstract com.syrus.AMFICOM.scheme.corba.AbstractSchemePort sourceAbstractSchemePort ();

  public abstract void sourceAbstractSchemePort (com.syrus.AMFICOM.scheme.corba.AbstractSchemePort newSourceAbstractSchemePort);

  public abstract com.syrus.AMFICOM.scheme.corba.AbstractSchemePort targetAbstractSchemePort ();

  public abstract void targetAbstractSchemePort (com.syrus.AMFICOM.scheme.corba.AbstractSchemePort newTargetAbstractSchemePort);


  /**
  						 * Getter returns physical length of this scheme link or scheme cable link.
  						 * @see #thisPhysicalLength
  						 */
  public abstract double physicalLength ();


  /**
  						 * Getter returns physical length of this scheme link or scheme cable link.
  						 * @see #thisPhysicalLength
  						 */
  public abstract void physicalLength (double newPhysicalLength);


  /**
  						 * Getter returns optical length of this scheme link or scheme cable link.
  						 * @see #thisOpticalLength
  						 */
  public abstract double opticalLength ();


  /**
  						 * Getter returns optical length of this scheme link or scheme cable link.
  						 * @see #thisOpticalLength
  						 */
  public abstract void opticalLength (double newOpticalLength);
} // class AbstractSchemeLink
