package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/AbstractSchemePort.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class AbstractSchemePort implements com.syrus.AMFICOM.general.corba.IStorableObject, com.syrus.AMFICOM.general.corba.Namable, com.syrus.AMFICOM.general.corba.Describable, com.syrus.AMFICOM.scheme.Characterizable, com.syrus.AMFICOM.general.Characterizable, com.syrus.AMFICOM.configuration.ComSyrusAmficomConfigurationAbstractSchemePort
{
  protected String thisName = null;
  protected String thisDescription = null;
  protected com.syrus.AMFICOM.general.Identifier schemeDeviceId = null;

 /**
 						 * Depending on implementation, may reference either {@link SchemeLink} or {@link SchemeCableLink}.
 						 */
  protected com.syrus.AMFICOM.general.Identifier abstractSchemeLinkId = null;

 /**
 						 * Depending on implementation, may reference either {@link com.syrus.AMFICOM.configuration.PortType port type} or {@link com.syrus.AMFICOM.configuration.PortType cable port type}.
 						 */
  protected com.syrus.AMFICOM.general.Identifier portTypeId = null;

 /**
 						 * Depending on implementation, may reference either {@link com.syrus.AMFICOM.configuration.Port port} or {@link com.syrus.AMFICOM.configuration.Port cable port}.
 						 */
  protected com.syrus.AMFICOM.general.Identifier portId = null;
  protected com.syrus.AMFICOM.general.Identifier measurementPortTypeId = null;
  protected com.syrus.AMFICOM.general.Identifier measurementPortId = null;
  protected com.syrus.AMFICOM.scheme.corba.AbstractSchemePortPackage.DirectionType thisDirectionType = null;
  protected com.syrus.AMFICOM.general.Identifier characteristicIds[] = null;

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeDevice schemeDevice ();

  public abstract void schemeDevice (com.syrus.AMFICOM.scheme.corba.SchemeDevice newSchemeDevice);


  /**
  						 * @see #abstractSchemeLinkId
  						 */
  public abstract com.syrus.AMFICOM.scheme.corba.AbstractSchemeLink abstractSchemeLink ();


  /**
  						 * @see #abstractSchemeLinkId
  						 */
  public abstract void abstractSchemeLink (com.syrus.AMFICOM.scheme.corba.AbstractSchemeLink newAbstractSchemeLink);

  public abstract com.syrus.AMFICOM.scheme.corba.AbstractSchemePortPackage.DirectionType directionType ();

  public abstract void directionType (com.syrus.AMFICOM.scheme.corba.AbstractSchemePortPackage.DirectionType newDirectionType);

} // class AbstractSchemePort
