package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/CableChannelingItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class CableChannelingItem implements com.syrus.AMFICOM.general.corba.IStorableObject, com.syrus.AMFICOM.general.corba.Namable, com.syrus.AMFICOM.general.corba.Describable, com.syrus.AMFICOM.map.ComSyrusAmficomMapCableChannelingItem
{
  protected String thisName = null;
  protected String thisDescription = null;
  protected int thisSequentialNumber = (int)0;
  protected com.syrus.AMFICOM.general.Identifier physicalLinkId = null;
  protected int thisRowX = (int)0;
  protected int thisPlaceY = (int)0;
  protected double thisStartSpare = (double)0;
  protected double thisEndSpare = (double)0;
  protected com.syrus.AMFICOM.general.Identifier startSiteNodeId = null;
  protected com.syrus.AMFICOM.general.Identifier endSiteNodeId = null;

  public abstract int sequentialNumber ();

  public abstract void sequentialNumber (int newSequentialNumber);

  public abstract int rowX ();

  public abstract void rowX (int newRowX);

  public abstract int placeY ();

  public abstract void placeY (int newPlaceY);

  public abstract double startSpare ();

  public abstract void startSpare (double newStartSpare);

  public abstract double endSpare ();

  public abstract void endSpare (double newEndSpare);

  public abstract com.syrus.AMFICOM.scheme.corba.CableChannelingItem cloneInstance ();
} // class CableChannelingItem
