package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/ISchemeProtoGroup.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public interface ISchemeProtoGroup extends com.syrus.AMFICOM.general.corba.IStorableObject, com.syrus.AMFICOM.general.corba.Namable, com.syrus.AMFICOM.general.corba.Describable, com.syrus.AMFICOM.resource.SchemeSymbolContainer
{
  public abstract com.syrus.AMFICOM.scheme.corba.SchemeProtoGroup parentSchemeProtoGroup ();


  /**
  						 * Transient attribute.
  						 */
  public abstract com.syrus.AMFICOM.scheme.corba.SchemeProtoGroup[] schemeProtoGroups ();


  /**
  						 * Transient attribute.
  						 */
  public abstract void schemeProtoGroups (com.syrus.AMFICOM.scheme.corba.SchemeProtoGroup[] newSchemeProtoGroups);


  /**
  						 * Transient attribute.
  						 */
  public abstract com.syrus.AMFICOM.scheme.corba.SchemeProtoElement[] schemeProtoElements ();


  /**
  						 * Transient attribute.
  						 */
  public abstract void schemeProtoElements (com.syrus.AMFICOM.scheme.corba.SchemeProtoElement[] newSchemeProtoElements);

} // interface ISchemeProtoGroup
