package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/PathElementPackage/Type.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public class PathElementType implements org.omg.CORBA.portable.IDLEntity {
	private static final long serialVersionUID = 3257565092399887665L;
private        int __value;
  private static int __size = 3;
  private static com.syrus.AMFICOM.scheme.corba.PathElementType[] __array = new com.syrus.AMFICOM.scheme.corba.PathElementType [__size];

  public static final int _SCHEME_CABLE_LINK = 0;
  public static final com.syrus.AMFICOM.scheme.corba.PathElementType SCHEME_CABLE_LINK = new com.syrus.AMFICOM.scheme.corba.PathElementType(_SCHEME_CABLE_LINK);
  public static final int _SCHEME_ELEMENT = 1;
  public static final com.syrus.AMFICOM.scheme.corba.PathElementType SCHEME_ELEMENT = new com.syrus.AMFICOM.scheme.corba.PathElementType(_SCHEME_ELEMENT);
  public static final int _SCHEME_LINK = 2;
  public static final com.syrus.AMFICOM.scheme.corba.PathElementType SCHEME_LINK = new com.syrus.AMFICOM.scheme.corba.PathElementType(_SCHEME_LINK);

  public int value ()
  {
    return this.__value;
  }

	public static com.syrus.AMFICOM.scheme.corba.PathElementType from_int (int value) {
		if (value >= 0 && value < __size)
			return __array[value];
		throw new org.omg.CORBA.BAD_PARAM();
	}

  protected PathElementType (int value)
  {
    this.__value = value;
    __array[this.__value] = this;
  }
} // class Type
