package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/SchemeProtoElement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class SchemeProtoElement implements com.syrus.AMFICOM.general.corba.IStorableObject, com.syrus.AMFICOM.general.corba.Namable, com.syrus.AMFICOM.general.corba.Describable, com.syrus.AMFICOM.resource.SchemeCellContainer, com.syrus.AMFICOM.scheme.Characterizable, com.syrus.AMFICOM.general.Characterizable, com.syrus.AMFICOM.configuration.ComSyrusAmficomConfigurationSchemeProtoElement
{
  protected String thisName = null;
  protected String thisDescription = null;
  protected com.syrus.AMFICOM.general.Identifier equipmentTypeId = null;
  protected com.syrus.AMFICOM.general.Identifier deviceIds[] = null;
  protected com.syrus.AMFICOM.general.Identifier linkIds[] = null;
  protected com.syrus.AMFICOM.general.Identifier protoElementIds[] = null;
  protected com.syrus.AMFICOM.general.Identifier symbolId = null;
  protected com.syrus.AMFICOM.general.Identifier parentId = null;
  protected String thisLabel = null;

 /**
 						 * Takes non-null value at pack time.
 						 */
  protected com.syrus.AMFICOM.general.Identifier ugoCellId = null;

 /**
 						 * Takes non-null value at pack time.
 						 */
  protected com.syrus.AMFICOM.general.Identifier schemeCellId = null;
  protected com.syrus.AMFICOM.general.Identifier characteristicIds[] = null;

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeDevice[] devices ();

  public abstract void devices (com.syrus.AMFICOM.scheme.corba.SchemeDevice[] newDevices);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeLink[] links ();

  public abstract void links (com.syrus.AMFICOM.scheme.corba.SchemeLink[] newLinks);


  /**
  						 * Getter returns an array of this node's child nodes.
  						 * @see #protoElementIds
  						 */
  public abstract com.syrus.AMFICOM.scheme.corba.SchemeProtoElement[] protoElements ();


  /**
  						 * Getter returns an array of this node's child nodes.
  						 * @see #protoElementIds
  						 */
  public abstract void protoElements (com.syrus.AMFICOM.scheme.corba.SchemeProtoElement[] newProtoElements);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeProtoGroup parent ();

  public abstract void parent (com.syrus.AMFICOM.scheme.corba.SchemeProtoGroup newParent);

  public abstract String label ();

  public abstract void label (String newLabel);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeProtoElement cloneInstance ();
} // class SchemeProtoElement
