package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/SchemeCablePort.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class SchemeCablePort extends com.syrus.AMFICOM.scheme.corba.AbstractSchemePort
{

  /**
  						 * @see AbstractSchemePort#abstractSchemeLinkId
  						 */
  public abstract com.syrus.AMFICOM.scheme.corba.SchemeCableLink schemeCableLink ();


  /**
  						 * @see AbstractSchemePort#abstractSchemeLinkId
  						 */
  public abstract void schemeCableLink (com.syrus.AMFICOM.scheme.corba.SchemeCableLink newSchemeCableLink);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeCablePort cloneInstance ();
} // class SchemeCablePort
