package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/SchemeLink.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class SchemeLink extends com.syrus.AMFICOM.scheme.corba.AbstractSchemeLink implements com.syrus.AMFICOM.configuration.ComSyrusAmficomConfigurationSchemeLink, com.syrus.AMFICOM.map.ComSyrusAmficomMapSchemeLink
{
  protected com.syrus.AMFICOM.general.Identifier siteId = null;


  /**
  						 * @see AbstractSchemeLink#sourceAbstractSchemePortId
  						 */
  public abstract com.syrus.AMFICOM.scheme.corba.SchemePort sourceSchemePort ();


  /**
  						 * @see AbstractSchemeLink#sourceAbstractSchemePortId
  						 */
  public abstract void sourceSchemePort (com.syrus.AMFICOM.scheme.corba.SchemePort newSourceSchemePort);


  /**
  						 * @see AbstractSchemeLink#targetAbstractSchemePortId
  						 */
  public abstract com.syrus.AMFICOM.scheme.corba.SchemePort targetSchemePort ();


  /**
  						 * @see AbstractSchemeLink#targetAbstractSchemePortId
  						 */
  public abstract void targetSchemePort (com.syrus.AMFICOM.scheme.corba.SchemePort newTargetSchemePort);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeLink cloneInstance ();
} // class SchemeLink
