package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/SchemePackage/SchemeType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public class SchemeKind implements org.omg.CORBA.portable.IDLEntity {
	private static final long serialVersionUID = 3616726075988784953L;
private        int __value;
  private static int __size = 8;
  private static com.syrus.AMFICOM.scheme.corba.SchemeKind[] __array = new com.syrus.AMFICOM.scheme.corba.SchemeKind [__size];

  public static final int _BUILDING = 0;
  public static final com.syrus.AMFICOM.scheme.corba.SchemeKind BUILDING = new com.syrus.AMFICOM.scheme.corba.SchemeKind(_BUILDING);
  public static final int _CABLE_SUBNETWORK = 1;
  public static final com.syrus.AMFICOM.scheme.corba.SchemeKind CABLE_SUBNETWORK = new com.syrus.AMFICOM.scheme.corba.SchemeKind(_CABLE_SUBNETWORK);
  public static final int _NETWORK = 2;
  public static final com.syrus.AMFICOM.scheme.corba.SchemeKind NETWORK = new com.syrus.AMFICOM.scheme.corba.SchemeKind(_NETWORK);
  public static final int _FLOOR = 3;
  public static final com.syrus.AMFICOM.scheme.corba.SchemeKind FLOOR = new com.syrus.AMFICOM.scheme.corba.SchemeKind(_FLOOR);
  public static final int _ROOM = 4;
  public static final com.syrus.AMFICOM.scheme.corba.SchemeKind ROOM = new com.syrus.AMFICOM.scheme.corba.SchemeKind(_ROOM);
  public static final int _RACK = 5;
  public static final com.syrus.AMFICOM.scheme.corba.SchemeKind RACK = new com.syrus.AMFICOM.scheme.corba.SchemeKind(_RACK);
  public static final int _BAY = 6;
  public static final com.syrus.AMFICOM.scheme.corba.SchemeKind BAY = new com.syrus.AMFICOM.scheme.corba.SchemeKind(_BAY);
  public static final int _CARDCAGE = 7;
  public static final com.syrus.AMFICOM.scheme.corba.SchemeKind CARDCAGE = new com.syrus.AMFICOM.scheme.corba.SchemeKind(_CARDCAGE);

  public int value ()
  {
    return this.__value;
  }

  public static com.syrus.AMFICOM.scheme.corba.SchemeKind from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected SchemeKind (int value)
  {
    this.__value = value;
    __array[this.__value] = this;
  }
} // class SchemeType
