package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/SchemeProtoGroup.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/


/**
					 * #01 in hierarchy.
					 */
public abstract class SchemeProtoGroup implements com.syrus.AMFICOM.scheme.corba.ISchemeProtoGroup
{
  protected com.syrus.AMFICOM.general.corba.StorableObject delegate = null;
  protected String thisName = null;
  protected String thisDescription = null;
  protected com.syrus.AMFICOM.general.Identifier symbolId = null;
  protected com.syrus.AMFICOM.general.Identifier parentSchemeProtoGroupId = null;

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeProtoGroup cloneInstance ();

  public abstract void setAttributes (long created, long modified, com.syrus.AMFICOM.general.Identifier creatorId, com.syrus.AMFICOM.general.Identifier modifierId, long version, String name, String description, com.syrus.AMFICOM.resource.corba.ImageResource_Transferable symbol, com.syrus.AMFICOM.scheme.corba.SchemeProtoGroup parentSchemeProtoGroup);
} // class SchemeProtoGroup
