package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/SchemeCableLink.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class SchemeCableLink extends com.syrus.AMFICOM.scheme.corba.AbstractSchemeLink implements com.syrus.AMFICOM.configuration.ComSyrusAmficomConfigurationSchemeCableLink
{
  protected com.syrus.AMFICOM.general.Identifier schemeCableThreadIds[] = null;
  protected com.syrus.AMFICOM.general.Identifier cableChannelingItemIds[] = null;


  /**
  						 * @see AbstractSchemeLink#sourceAbstractSchemePortId
  						 */
  public abstract com.syrus.AMFICOM.scheme.corba.SchemeCablePort sourceSchemeCablePort ();


  /**
  						 * @see AbstractSchemeLink#sourceAbstractSchemePortId
  						 */
  public abstract void sourceSchemeCablePort (com.syrus.AMFICOM.scheme.corba.SchemeCablePort newSourceSchemeCablePort);


  /**
  						 * @see AbstractSchemeLink#targetAbstractSchemePortId
  						 */
  public abstract com.syrus.AMFICOM.scheme.corba.SchemeCablePort targetSchemeCablePort ();


  /**
  						 * @see AbstractSchemeLink#targetAbstractSchemePortId
  						 */
  public abstract void targetSchemeCablePort (com.syrus.AMFICOM.scheme.corba.SchemeCablePort newTargetSchemeCablePort);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeCableThread[] schemeCableThreads ();

  public abstract void schemeCableThreads (com.syrus.AMFICOM.scheme.corba.SchemeCableThread[] newSchemeCableThreads);

  public abstract com.syrus.AMFICOM.scheme.corba.CableChannelingItem[] cableChannelingItems ();

  public abstract void cableChannelingItems (com.syrus.AMFICOM.scheme.corba.CableChannelingItem[] newCableChannelingItems);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeCableLink cloneInstance ();
} // class SchemeCableLink
