package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/SchemeMonitoringSolution.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class SchemeMonitoringSolution implements com.syrus.AMFICOM.general.corba.IStorableObject, com.syrus.AMFICOM.general.corba.Namable, com.syrus.AMFICOM.general.corba.Describable
{
  protected String thisName = null;
  protected String thisDescription = null;
  protected com.syrus.AMFICOM.general.Identifier schemeId = null;
  protected double thisPrice = (double)0;
  protected com.syrus.AMFICOM.general.Identifier schemePathIds[] = null;

  public abstract com.syrus.AMFICOM.scheme.corba.Scheme scheme ();

  public abstract void scheme (com.syrus.AMFICOM.scheme.corba.Scheme newScheme);

  public abstract double price ();

  public abstract void price (double newPrice);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemePath[] schemePaths ();

  public abstract void schemePaths (com.syrus.AMFICOM.scheme.corba.SchemePath[] newSchemePaths);
} // class SchemeMonitoringSolution
