package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/SchemeDevice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class SchemeDevice implements com.syrus.AMFICOM.general.corba.IStorableObject, com.syrus.AMFICOM.general.corba.Namable, com.syrus.AMFICOM.general.corba.Describable, com.syrus.AMFICOM.scheme.Characterizable, com.syrus.AMFICOM.general.Characterizable
{
  protected String thisName = null;
  protected String thisDescription = null;
  protected com.syrus.AMFICOM.general.Identifier schemePortIds[] = null;
  protected com.syrus.AMFICOM.general.Identifier schemeCablePortIds[] = null;
  protected com.syrus.AMFICOM.general.Identifier characteristicIds[] = null;

  public abstract com.syrus.AMFICOM.scheme.corba.SchemePort[] schemePorts ();

  public abstract void schemePorts (com.syrus.AMFICOM.scheme.corba.SchemePort[] newSchemePorts);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeCablePort[] schemeCablePorts ();

  public abstract void schemeCablePorts (com.syrus.AMFICOM.scheme.corba.SchemeCablePort[] newSchemeCablePorts);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeDevice cloneInstance ();
} // class SchemeDevice
