package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/SchemePath.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class SchemePath implements com.syrus.AMFICOM.general.corba.IStorableObject, com.syrus.AMFICOM.general.corba.Namable, com.syrus.AMFICOM.general.corba.Describable, com.syrus.AMFICOM.scheme.Characterizable, com.syrus.AMFICOM.general.Characterizable, com.syrus.AMFICOM.configuration.ComSyrusAmficomConfigurationSchemePath
{
  protected String thisName = null;
  protected String thisDescription = null;
  protected com.syrus.AMFICOM.general.Identifier _typeId = null;
  protected com.syrus.AMFICOM.general.Identifier startDeviceId = null;
  protected com.syrus.AMFICOM.general.Identifier endDeviceId = null;
  protected com.syrus.AMFICOM.general.Identifier pathId = null;
  protected com.syrus.AMFICOM.general.Identifier links[] = null;
  protected com.syrus.AMFICOM.general.Identifier characteristicIds[] = null;
  protected com.syrus.AMFICOM.general.Identifier schemeId = null;

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeElement startDevice ();

  public abstract void startDevice (com.syrus.AMFICOM.scheme.corba.SchemeElement newStartDevice);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeElement endDevice ();

  public abstract void endDevice (com.syrus.AMFICOM.scheme.corba.SchemeElement newEndDevice);

  public abstract com.syrus.AMFICOM.scheme.corba.PathElement[] links ();

  public abstract void links (com.syrus.AMFICOM.scheme.corba.PathElement[] newLinks);

  public abstract com.syrus.AMFICOM.scheme.corba.Scheme scheme ();

  public abstract void scheme (com.syrus.AMFICOM.scheme.corba.Scheme newScheme);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemePath cloneInstance ();
} // class SchemePath
