package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/SchemeOptimizeInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class SchemeOptimizeInfo implements com.syrus.AMFICOM.general.corba.IStorableObject, com.syrus.AMFICOM.general.corba.Namable, com.syrus.AMFICOM.general.corba.Describable
{
  protected String thisName = null;
  protected String thisDescription = null;
  protected com.syrus.AMFICOM.general.Identifier schemeId = null;
  protected com.syrus.AMFICOM.general.Identifier schemeMonitoringSolutionId = null;
  protected com.syrus.AMFICOM.scheme.corba.SchemeOptimizeInfoPackage.OptimizationMode thisOptimizationMode = null;
  protected double thisIterations = (double)0;
  protected double thisPrice = (double)0;
  protected double thisWavelength = (double)0;
  protected double thisLenMargin = (double)0;
  protected double thisMutationRate = (double)0;
  protected double thisMutationDegree = (double)0;
  protected double thisRtuDeleteProb = (double)0;
  protected double thisRtuCreateProb = (double)0;
  protected double thisNodesSpliceProb = (double)0;
  protected double thisNodesCutProb = (double)0;
  protected double thisSurvivorRate = (double)0;
  protected double thisReflPrices[] = null;
  protected String thisReflNames[] = null;
  protected double thisReflRanges[] = null;
  protected double thisSwitchPrices[] = null;
  protected double thisSwitchNports[] = null;
  protected String thisSwitchNames[] = null;

  public abstract com.syrus.AMFICOM.scheme.corba.Scheme scheme ();

  public abstract void scheme (com.syrus.AMFICOM.scheme.corba.Scheme newScheme);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeMonitoringSolution schemeMonitoringSolution ();

  public abstract void schemeMonitoringSolution (com.syrus.AMFICOM.scheme.corba.SchemeMonitoringSolution newSchemeMonitoringSolution);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeOptimizeInfoPackage.OptimizationMode optimizationMode ();

  public abstract void optimizationMode (com.syrus.AMFICOM.scheme.corba.SchemeOptimizeInfoPackage.OptimizationMode newOptimizationMode);

  public abstract double iterations ();

  public abstract void iterations (double newIterations);

  public abstract double price ();

  public abstract void price (double newPrice);

  public abstract double wavelength ();

  public abstract void wavelength (double newWavelength);

  public abstract double lenMargin ();

  public abstract void lenMargin (double newLenMargin);

  public abstract double mutationRate ();

  public abstract void mutationRate (double newMutationRate);

  public abstract double mutationDegree ();

  public abstract void mutationDegree (double newMutationDegree);

  public abstract double rtuDeleteProb ();

  public abstract void rtuDeleteProb (double newRtuDeleteProb);

  public abstract double rtuCreateProb ();

  public abstract void rtuCreateProb (double newRtuCreateProb);

  public abstract double nodesSpliceProb ();

  public abstract void nodesSpliceProb (double newNodesSpliceProb);

  public abstract double nodesCutProb ();

  public abstract void nodesCutProb (double newNodesCutProb);

  public abstract double survivorRate ();

  public abstract void survivorRate (double newSurvivorRate);

  public abstract double[] reflPrices ();

  public abstract void reflPrices (double[] newReflPrices);

  public abstract String[] reflNames ();

  public abstract void reflNames (String[] newReflNames);

  public abstract double[] reflRanges ();

  public abstract void reflRanges (double[] newReflRanges);

  public abstract double[] switchPrices ();

  public abstract void switchPrices (double[] newSwitchPrices);

  public abstract double[] switchNports ();

  public abstract void switchNports (double[] newSwitchNports);

  public abstract String[] switchNames ();

  public abstract void switchNames (String[] newSwitchNames);
} // class SchemeOptimizeInfo
