package com.syrus.AMFICOM.scheme.corba;


/**
* com/syrus/AMFICOM/scheme/corba/Scheme.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public abstract class Scheme implements com.syrus.AMFICOM.general.corba.IStorableObject, com.syrus.AMFICOM.general.corba.Namable, com.syrus.AMFICOM.general.corba.Describable, com.syrus.AMFICOM.resource.SchemeCellContainer, com.syrus.AMFICOM.administration.ComSyrusAmficomAdministrationScheme, com.syrus.AMFICOM.map.ComSyrusAmficomMapScheme
{
  protected String thisName = null;
  protected String thisDescription = null;
  protected com.syrus.AMFICOM.scheme.corba.SchemePackage.Type thisType = null;

 /**
 						 * Value is assigned automatically.
 						 */
  protected com.syrus.AMFICOM.general.Identifier domainId = null;
  protected com.syrus.AMFICOM.general.Identifier schemeElementIds[] = null;
  protected com.syrus.AMFICOM.general.Identifier schemeLinkIds[] = null;
  protected com.syrus.AMFICOM.general.Identifier schemeCableLinkIds[] = null;
  protected com.syrus.AMFICOM.general.Identifier schemeMonitoringSolutionId = null;
  protected com.syrus.AMFICOM.general.Identifier symbolId = null;
  protected String thisLabel = null;

 /**
 						 * Takes non-null value at pack time.
 						 */
  protected com.syrus.AMFICOM.general.Identifier ugoCellId = null;

 /**
 						 * Takes non-null value at pack time.
 						 */
  protected com.syrus.AMFICOM.general.Identifier schemeCellId = null;
  protected int thisWidth = (int)0;
  protected int thisHeight = (int)0;
  protected com.syrus.AMFICOM.general.Identifier mapId = null;

  public abstract com.syrus.AMFICOM.scheme.corba.SchemePackage.Type type ();

  public abstract void type (com.syrus.AMFICOM.scheme.corba.SchemePackage.Type newType);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeElement[] schemeElements ();

  public abstract void schemeElements (com.syrus.AMFICOM.scheme.corba.SchemeElement[] newSchemeElements);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeLink[] schemeLinks ();

  public abstract void schemeLinks (com.syrus.AMFICOM.scheme.corba.SchemeLink[] newSchemeLinks);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeCableLink[] schemeCableLinks ();

  public abstract void schemeCableLinks (com.syrus.AMFICOM.scheme.corba.SchemeCableLink[] newSchemeCableLinks);

  public abstract com.syrus.AMFICOM.scheme.corba.SchemeMonitoringSolution schemeMonitoringSolution ();

  public abstract void schemeMonitoringSolution (com.syrus.AMFICOM.scheme.corba.SchemeMonitoringSolution newSchemeMonitoringSolution);

  public abstract String label ();

  public abstract void label (String newLabel);

  public abstract int width ();

  public abstract void width (int newWidth);

  public abstract int height ();

  public abstract void height (int newHeight);

  public abstract com.syrus.AMFICOM.scheme.corba.Scheme cloneInstance ();
} // class Scheme
