/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syrus_AMFICOM_agent_Transceiver */

#ifndef _Included_com_syrus_AMFICOM_agent_Transceiver
#define _Included_com_syrus_AMFICOM_agent_Transceiver
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: measurement_id */
/* Inaccessible static: par_names */
/* Inaccessible static: par_values */
/*
 * Class:     com_syrus_AMFICOM_agent_Transceiver
 * Method:    call
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_syrus_AMFICOM_agent_Transceiver_call
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_syrus_AMFICOM_agent_Transceiver
 * Method:    read1
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_syrus_AMFICOM_agent_Transceiver_read1
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_syrus_AMFICOM_agent_Transceiver
 * Method:    push1
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_syrus_AMFICOM_agent_Transceiver_push1
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
