@@set.sql
@@setmelink.sql
@@setparameter.sql
@@measurementsetup.sql
@@measurementsetupmelink.sql
@@crontemporalpattern.sql
@@periodicaltemporalpattern.sql
@@intervalstemporalpattern.sql
@@intervalstemporalpatternoffsetiddur.sql
@@test.sql
@@measurementsetuptestlink.sql
@@measurement.sql
@@analysis.sql
@@evaluation.sql
@@modeling.sql
@@result.sql
@@resultparameter.sql
