#!/bin/bash


JAVA=$JAVA_HOME/bin/java
LIB=$HOME/work/lib
DEVLIB=$HOME/work/devlib
TRANSCEIVER=./transceiver
DADARA=./dadara
ORACLECLASSPATH=$JDEV_HOME/jdbc/lib/classes12.jar
APPCLASSPATH=$DEVLIB/mcm.jar:$DEVLIB/mcm_interface.jar:$DEVLIB/measurementserver_interface.jar:$DEVLIB/measurement.jar:$DEVLIB/ServerInterface_General.jar:$LIB/util.jar:$LIB/io.jar:$LIB/Server.jar

exec $JAVA -Djava.library.path=$TRANSCEIVER:$DADARA -classpath $APPCLASSPATH:$ORACLECLASSPATH com.syrus.AMFICOM.mcm.MeasurementControlModule
