/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syrus_AMFICOM_analysis_AnalysisManager */

#ifndef _Included_com_syrus_AMFICOM_analysis_AnalysisManager
#define _Included_com_syrus_AMFICOM_analysis_AnalysisManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: defaultMinuitParams */
/*
 * Class:     com_syrus_AMFICOM_analysis_AnalysisManager
 * Method:    gauss
 * Signature: ([DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_syrus_AMFICOM_analysis_AnalysisManager_gauss
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdouble);

/*
 * Class:     com_syrus_AMFICOM_analysis_AnalysisManager
 * Method:    analyse
 * Signature: (I[DDIDDDDDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_syrus_AMFICOM_analysis_AnalysisManager_analyse
  (JNIEnv *, jclass, jint, jdoubleArray, jdouble, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
