#ifndef _ADMINISTRATION_IDL_
#define _ADMINISTRATION_IDL_

#include <general.idl>

module com {
module syrus {
module AMFICOM {
module administration {
module corba {

	struct PermissionAttributes_Transferable {
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable id;
		long long created;
		long long modified;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable creator_id;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable modifier_id;
	  wstring name;
	  wstring codename;
	  wstring rwx;
	  wstring deny_message;
	  com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable group_ids;
	  com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable category_ids;
	};

	struct Domain_Transferable {
		com::syrus::AMFICOM::general::corba::Identifier_Transferable id;
		long long created;
		long long modified;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable creator_id;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable modifier_id;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable domain_id;
		wstring name;
		wstring description;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable owner_id;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable permission_attributes_id;
		com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable domain_ids;
	};

	typedef sequence <Domain_Transferable> DomainSeq_Transferable;

	struct OperatorCategory_Transferable {
		com::syrus::AMFICOM::general::corba::Identifier_Transferable id;
		long long created;
		long long modified;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable creator_id;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable modifier_id;
		wstring name;
		wstring codename;
		wstring description;
		com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable user_ids;
	};

	typedef sequence <OperatorCategory_Transferable> OperatorCategorySeq_Transferable;

	struct OperatorGroup_Transferable {
		com::syrus::AMFICOM::general::corba::Identifier_Transferable id;
		long long created;
		long long modified;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable creator_id;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable modifier_id;
		wstring name;
		wstring codename;
		wstring description;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable owner_id;
		com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable user_ids;
		com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable exec_ids;
	};

	typedef sequence <OperatorGroup_Transferable> OperatorGroupSeq_Transferable;

	struct OperatorProfile_Transferable {
		com::syrus::AMFICOM::general::corba::Identifier_Transferable id;
		long long created;
		long long modified;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable creator_id;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable modifier_id;
		wstring name;
		wstring codename;
		wstring description;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable user_id;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable owner_id;
		wstring login;
		com::syrus::AMFICOM::general::corba::octetSeq password;
		long long password_expiry;
		long long last_login;
		wstring status;
		wstring state;
		long long disabled;
		wstring disabled_comments;
		wstring priority;
		wstring logfile;
		com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable category_ids;
		com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable group_ids;
		wstring first_name;
		wstring second_name;
		wstring last_name;
		wstring phone_work;
		wstring phone_home;
		wstring phone_mobile;
		wstring phone_emergency;
		wstring pager_phone;
		wstring pager_number;
		wstring sms_number;
		wstring address;
		wstring language;
		wstring organization;
		wstring e_mail;
	};

	typedef sequence <OperatorProfile_Transferable> OperatorProfileSeq_Transferable;

	struct AccessIdentity_Transferable {
		long long started;
		wstring username;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable user_id;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable sess_id;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable domain_id;
	};

	typedef sequence <AccessIdentity_Transferable> AccessIdentitySeq_Transferable;

	struct User_Transferable {
		com::syrus::AMFICOM::general::corba::Identifier_Transferable id;
		long long created;
		long long modified;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable creator_id;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable modifier_id;
		wstring login;
		wstring type;
		long long last_login;
		long long logged;
		long sessions;
		com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable category_ids;
		com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable group_ids;
	};

	typedef sequence <User_Transferable> UserSeq_Transferable;

	struct CommandPermissionAttributes_Transferable	{
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable id;
	  long long created;
	  long long modified;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable creator_id;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable modifier_id;
	  wstring rwx;
/*
	  boolean userR;
	  boolean userW;
	  boolean userX;
	  boolean groupR;
	  boolean groupW;
	  boolean groupX;
	  boolean otherR;
	  boolean otherW;
	  boolean otherX;
*/
	  com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable group_ids;
	  com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable category_ids;
	  wstring owner_id;
	  wstring name;
	  wstring codename;
	  wstring whyRejected;
	};

	typedef sequence <CommandPermissionAttributes_Transferable> CommandPermissionAttributesSeq_Transferable;

	struct Server_Transferable {
		com::syrus::AMFICOM::general::corba::Identifier_Transferable id;
		long long created;
		long long modified;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable creator_id;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable modifier_id;
		wstring name;
		wstring description;
		wstring location;
		wstring contact;
		wstring hostname;
		long sessions;
		com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable mcm_ids; 
	};

	typedef sequence <Server_Transferable> ServerSeq_Transferable;

	struct MCM_Transferable {
		com::syrus::AMFICOM::general::corba::Identifier_Transferable id;
		long long created;
		long long modified;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable creator_id;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable modifier_id;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable server_id;
		wstring name;
		wstring description;
		wstring location;
		wstring contact;
		wstring hostname;
		com::syrus::AMFICOM::general::corba::IdentifierSeq_Transferable kis_ids;
	};

	typedef sequence <MCM_Transferable> AgentSeq_Transferable;

	struct Client_Transferable {
		com::syrus::AMFICOM::general::corba::Identifier_Transferable id;
	  long long created;
	  long long modified;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable creator_id;
	  com::syrus::AMFICOM::general::corba::Identifier_Transferable modifier_id;
		wstring name;
		wstring version;
		com::syrus::AMFICOM::general::corba::Identifier_Transferable licence_id;
		wstring location;
		wstring contact;
		wstring hostname;
	};

	typedef sequence <Client_Transferable> ClientSeq_Transferable;
};
};
};
};
};

#endif