#!/bin/bash

JUNITCLASSPATH=/mnt/d/eclipse/3.1M4/plugins/org.junit_3.8.1/junit.jar
JDBCCLASSPATH=$ORACLE_HOME/jdbc/lib/ojdbc14.jar:$ORACLE_HOME/jdbc/lib/orai18n.jar
LIB=../lib
APPCLASSPATH=$LIB/util.jar:$LIB/general.jar

java -classpath $APPCLASSPATH:$JDBCCLASSPATH:$JUNITCLASSPATH:../general_v1/classes:./classes junit.textui.TestRunner com.syrus.AMFICOM.event.TestEventType
