#!/bin/bash


JAVA=$JAVA_HOME/bin/java
LIB=../lib
TRANSCEIVER=./transceiver
DADARA=./dadara
ORACLECLASSPATH=$ORACLE_HOME/jdbc/lib/classes12.jar
APPCLASSPATH=$LIB/mserver.jar:$LIB/measurement.jar:$LIB/configuration.jar:$LIB/general.jar:$LIB/util.jar

exec $JAVA -classpath $APPCLASSPATH:$ORACLECLASSPATH com.syrus.AMFICOM.mserver.MeasurementServer
