#!/bin/bash


JAVA=$JAVA_HOME/bin/java
LIB=../lib
ORACLECLASSPATH=$ORACLE_HOME/jdbc/lib/classes12.jar
APPCLASSPATH=$LIB/mserver.jar:$LIB/mcm_interface.jar:$LIB/measurement.jar:$LIB/configuration.jar:$LIB/general.jar:$LIB/servermisc.jar:$LIB/util.jar

exec $JAVA -server -classpath $APPCLASSPATH:$ORACLECLASSPATH com.syrus.AMFICOM.mserver.MeasurementServer
