#!/bin/bash


JAVA=$JAVA_HOME/bin/java
LIB=../lib
TRANSCEIVER=./transceiver
DADARA=./dadara
ORACLECLASSPATH=$ORACLE_HOME/jdbc/lib/classes12.jar
APPCLASSPATH=$LIB/mcm.jar:$LIB/mcm_interface.jar:$LIB/measurementserver_interface.jar:$LIB/measurement.jar:$LIB/configuration.jar:$LIB/general.jar:$LIB/util.jar

exec $JAVA -Djava.library.path=$TRANSCEIVER:$DADARA -classpath $APPCLASSPATH:$ORACLECLASSPATH com.syrus.AMFICOM.mcm.MeasurementControlModule
