/*
 * $Id: AMFICOMKIS.idl,v 1.2 2004/09/29 14:48:51 bass Exp $
 *
 * Copyright © 2004 Syrus Systems.
 * Научно-технический центр.
 * Проект: АМФИКОМ.
 */

#ifndef AMFICOMKIS_IDL
#define AMFICOMKIS_IDL

#include <streams.idl>

#include "KIS.idl"

module com {
	module syrus {
		module AMFICOM {
			module CORBA {
				interface AMFICOMKIS {
					KIS::TestSeq_Transferable queryTests(in KIS::AgentIdentity_Transferable agentid, in long long interval) raises (General::AMFICOMRemoteException);

					::CORBA::WStringSeq queryAbortedTests(in KIS::AgentIdentity_Transferable agentid) raises (General::AMFICOMRemoteException);

					long reportResult(in KIS::AgentIdentity_Transferable agentid, in KIS::Result_Transferable result) raises (General::AMFICOMRemoteException);

					KIS::KISIdentitySeq_Transferable getKISIdentities(in KIS::AgentIdentity_Transferable agentid) raises (General::AMFICOMRemoteException);
				};
			};
		};
	};
};

#endif
