@@parametertype
@@measurementtype
@@analysistype
@@evaluationtype
@@modelingtype
@@mnttyppartyplink
@@anatyppartyplink
@@evatyppartyplink
@@modtyppartyplink
@@mnttypanatypevatyp
@@mnttypmeasporttyplink
