#!/bin/bash

# This script can be used to run tests from console

TEST_CLASS=Setup3
TEST_PACKAGE=com.syrus.AMFICOM.setup
#TEST_CLASS=TestLRUMap
#TEST_PACKAGE=com.syrus.util
#TEST_CLASS=TestIdentifier
#TEST_PACKAGE=com.syrus.AMFICOM.general
#TEST_CLASS=TestSystemUser
#TEST_PACKAGE=com.syrus.AMFICOM.administration
#TEST_CLASS=TestDomain
#TEST_PACKAGE=com.syrus.AMFICOM.administration

LIBDIR=../lib
EXTLIBDIR=../../extlib
APPCLASSPATH=$LIBDIR/general.jar:$LIBDIR/administration.jar:$LIBDIR/configuration.jar:$LIBDIR/scheme.jar:$LIBDIR/resource.jar:$LIBDIR/filter.jar:$LIBDIR/measurement.jar:$LIBDIR/event.jar:$LIBDIR/csbridge.jar:$LIBDIR/reflectometry.jar:$LIBDIR/leserver_interface.jar:$LIBDIR/mserver_interface.jar:$LIBDIR/cmserver_interface.jar:$LIBDIR/mcm_interface.jar:$LIBDIR/commonclient.jar:$LIBDIR/util.jar
XMLCLASSPATH=$LIBDIR/generalxml.jar:$LIBDIR/configurationxml.jar
EXTCLASSPATH=$EXTLIBDIR/trove.jar:$XMLBEANS_HOME/lib/xbean.jar:$XMLBEANS_HOME/build/lib/jsr173_api.jar
JUNITCLASSPATH=$ECLIPSE_HOME/plugins/org.junit_3.8.1/junit.jar
JDBCCLASSPATH=$ORACLE_HOME/jdbc/lib/ojdbc14.jar:$ORACLE_HOME/jdbc/lib/orai18n.jar

java -ea -classpath ${APPCLASSPATH}:${XMLCLASSPATH}:${EXTCLASSPATH}:${JDBCCLASSPATH}:${JUNITCLASSPATH}:./classes junit.textui.TestRunner ${TEST_PACKAGE}.${TEST_CLASS}
