package com.syrus.AMFICOM.scheme;


/**
* com/syrus/AMFICOM/scheme/Characterizable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public interface Characterizable
{
  public abstract com.syrus.AMFICOM.general.corba.Characteristic_Transferable[] characteristics ();

  public abstract void characteristics (com.syrus.AMFICOM.general.corba.Characteristic_Transferable[] newCharacteristics);


  /**
  					 * Accessor pair for <code>sequence&lt;{@link com.syrus.AMFICOM.general.Characteristic}&gt;</code>.
  					 */
  public abstract CharacteristicSeqContainer characteristicsImpl ();


  /**
  					 * Accessor pair for <code>sequence&lt;{@link com.syrus.AMFICOM.general.Characteristic}&gt;</code>.
  					 */
  public abstract void characteristicsImpl (CharacteristicSeqContainer newCharacteristicsImpl);

} // interface Characterizable
