#
# $Id: Makefile,v 1.3 2004/09/14 14:07:21 bass Exp $
#
# vim:set ft=make:
#

MODULE_NAME = admin_v1

LIBNAME = administrate.jar

JAVACFLAGS = -source 1.4
SUNJAVACFLAGS = -target 1.4
JIKESFLAGS = -target 1.4.2

include ../tools/Makefile.inc
$(call checkenve,JAVA_HOME)
$(call checkenve,ORACLE_HOME)

.PHONY: export
export:
$(error Not yet implemented)
