CREATE USER amficom
	PROFILE DEFAULT
	IDENTIFIED BY amficom
	DEFAULT TABLESPACE users
	TEMPORARY TABLESPACE temp
	QUOTA UNLIMITED ON temp
	QUOTA UNLIMITED ON users
	ACCOUNT UNLOCK;

GRANT CREATE SESSION TO amficom;
GRANT CREATE TABLE TO amficom;
GRANT CREATE TYPE TO amficom;
GRANT CREATE SEQUENCE TO amficom;
