package com.syrus.AMFICOM.scheme.corba.SchemeOptimizeInfoPackage;


/**
* com/syrus/AMFICOM/scheme/corba/SchemeOptimizeInfoPackage/OptimizationMode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-vt.idl
* 4 Март 2005 г. 18:11:15 MSK
*/

public class OptimizationMode implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 1;
  private static com.syrus.AMFICOM.scheme.corba.SchemeOptimizeInfoPackage.OptimizationMode[] __array = new com.syrus.AMFICOM.scheme.corba.SchemeOptimizeInfoPackage.OptimizationMode [__size];

  public static final int __DEFAULT = 0;
  public static final com.syrus.AMFICOM.scheme.corba.SchemeOptimizeInfoPackage.OptimizationMode _DEFAULT = new com.syrus.AMFICOM.scheme.corba.SchemeOptimizeInfoPackage.OptimizationMode(__DEFAULT);

  public int value ()
  {
    return __value;
  }

  public static com.syrus.AMFICOM.scheme.corba.SchemeOptimizeInfoPackage.OptimizationMode from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected OptimizationMode (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class OptimizationMode
