#!/bin/bash

DATE_REGEXP=2[0-9]{3}[0-1][0-9][0-3][0-9]
if [ -x /usr/xpg4/bin/sed ]
then
	SED=/usr/xpg4/bin/sed
else
	SED=sed
fi
if [ -x /usr/xpg4/bin/egrep ]
then
	EGREP=/usr/xpg4/bin/egrep
else
	EGREP=egrep
fi

archive() {
	if [ $# -ne 2 ]
	then
		echo "Функция archive: неправильное количество аргументов"
		exit 1
	fi
	LOGS_DIR=$1
	OVERRIDE=$2
	TODAY=`date +%Y%m%d`
	LOGS_SUB_DIRS=`ls -1 $LOGS_DIR | $EGREP -v $TODAY | $EGREP "^${DATE_REGEXP}$"`
	for log_sub_dir in $LOGS_SUB_DIRS
	do
		log_sub_dir_full=$LOGS_DIR/$log_sub_dir
		if [ ! -d $log_sub_dir_full ]
		then
			echo "Не каталог -- $log_sub_dir_full"
			continue
		fi

		arch_file=$log_sub_dir.tar.bz2
		echo "Архивирую каталог $log_sub_dir в файл $arch_file"
		if [ -f $LOGS_DIR/$arch_file -a $OVERRIDE = "0" ]
		then
			echo "Архивирование отложено по причине существования файла"
			continue
		fi

		tar -cvf - -C $LOGS_DIR $log_sub_dir | bzip2 -9 > $LOGS_DIR/$arch_file
		ret_code=$?
		if [ ret_code != "0" ]
		then
			echo "Удаляю каталог $log_sub_dir"
			rm -rf $log_sub_dir_full
		else
			echo "Ошибка при архивировании каталога $log_sub_dir; код выхода: $ret_code"
		fi
	done
}

delete_old() {
	if [ $# -ne 2 ]
	then
		echo "Функция delete_old: неправильное количество аргументов"
		exit 1
	fi
	LOGS_DIR=$1
	DELETE_DATE=$2

	ARCH_FILES=`ls -1 $LOGS_DIR | $EGREP "^${DATE_REGEXP}.tar.bz2$"`
	for arch_file in $ARCH_FILES
	do
		arch_file_full=$LOGS_DIR/$arch_file
		arch_file_date=`echo $arch_file | $SED 's|.tar.bz2||'`
		if [ $((arch_file_date)) -le $((DELETE_DATE)) ]
		then
			echo "Удаляю архивный файл: $arch_file"
			rm -f $arch_file_full
		fi
	done
}

print_usage() {
	cat <<EOF
Архивирование каталогов журналов и удаление старых архивов.
ВНИМАНИЕ! Поддерживается только следующий формат даты: "ГГГГММДД"
Использование: `basename $0` [-p путь_к_каталогу_журналов] [-a [-f]] [-d срок_давности] [-h]
Аргументы:
-p путь_к_каталогу_журналов
	Путь к каталогу, где хранятся подкаталоги файлов журналов.
	По умолчанию -- текущий каталог.
-a
	Провести архивирование подкаталогов с файлами журналов.
-f
	В случае обнаружения архива, перезаписать его.
-d срок_давности
	Удалять старые архивы, начиная с указанного срока давности.
	Срок давности может задаваться либо датой в вышеуказанном формате,
	либо так:
	day -- один день;
	week -- одна неделя;
	month -- один месяц;
	year -- один год.
-h
	Вывести справку.
EOF
}


LOGS_DIR=
ARCHIVE=0
OVERRIDE=0
DELETE_DATE=
while [ $# -gt 0 ]
do
	case "$1" in
		-h)
			print_usage
			exit 0
			;;
		-p)
			shift
			if [ $# -gt 0 -a "$1" = `echo "$1" | $SED 's|-[a-zA-Z]||'` ]
			then
				LOGS_DIR=$1
			else
				echo "Не указан путь к каталогу журналов"
				exit 1
			fi
			shift
			;;
		-a)
			ARCHIVE=1
			shift
			if [ "$1" = "-f" ]
			then
				OVERRIDE=1
				shift
			fi
			;;
		-d)
			shift
			if [ $# -gt 0 ]
			then
				DELETE_DATE=$1
				case "$DELETE_DATE" in
					day)
						DELETE_DATE=`date -d -1day +%Y%m%d`
						;;
					week)
						DELETE_DATE=`date -d -1week +%Y%m%d`
						;;
					month)
						DELETE_DATE=`date -d -1month +%Y%m%d`
						;;
					year)
						DELETE_DATE=`date -d -1year +%Y%m%d`
						;;
					*)
						if [ x`echo "$DELETE_DATE" | $SED "s|$DATE_REGEXP||"` != "x" ]
						then
							echo "Неправильный формат даты"
							exit 1
						fi
				esac
				
				
			else
				echo "Не указана дата"
				exit 1
			fi
			shift
			;;
		*)
			echo "Неверный аргумент: $1"
			echo
			print_usage
			exit 1
	esac
done

if [ x$LOGS_DIR = "x" ]
then
	LOGS_DIR=.
fi
if [ ! -d $LOGS_DIR ]
then
	echo "Каталог не найден: $LOGS_DIR"
	exit 1
fi
echo "Работаю в каталоге: $LOGS_DIR"

if [ $ARCHIVE = "1" ]
then
	archive $LOGS_DIR $OVERRIDE
fi

if [ x$DELETE_DATE != "x" ]
then
	delete_old $LOGS_DIR $DELETE_DATE
fi

