#!/bin/sh

# chkconfig: 345 89 15
# description: Starts Oracle listener; then starts database instance \
#              according to /etc/oratab

ORA_HOME=/orabase/oracle/product/10.1.0/db_1
ORA_OWNER=oracle

if [ ! -f $ORA_HOME/bin/dbstart -o ! -d $ORA_HOME ]; then
	echo "Oracle startup: cannot start"
	exit
fi

case "${1}" in
	'start')
#Start the Oracle Databases:
		su - ${ORA_OWNER} -c "$ORA_HOME/bin/lsnrctl start LISTENER"
		su - ${ORA_OWNER} -c $ORA_HOME/bin/dbstart
		;;
	'stop')
		su - ${ORA_OWNER} -c $ORA_HOME/bin/dbshut
		;;
esac
