#!/bin/sh

# chkconfig: 345 97 14
# description: Starts ORB daemon

ORBD=`which orbd`
GREP=/usr/xpg4/bin/grep
SED=/usr/xpg4/bin/sed
if [ ! -x ${ORBD} ]
then
	echo "orbd is missing or is not executable; exiting..."
	exit 1
fi

ORBD_DIR=/tmp/.orb.db
PIDFILE=${ORBD_DIR}/orbd.pid

killprocess() {
	pid=$1
	psline=`ps -eo "pid,args" | ${GREP} -E "^[ \t]*${pid}[ \t]"`
	if [ ! -z "${psline}" ]
	then
		args=`echo ${psline} | ${SED} "s/^\s*${pid}\s*//g"`
		echo "Args: ${args}"

		kill -9 ${pid}
		sleep 10
		killprocess ${pid}
	fi
}


case "$1" in
	start)
		if [ -f "${PIDFILE}" ]
		then
			pid=`cat ${PIDFILE}`
			psline=`ps -eo "pid,args" | ${GREP} -E "^[ \t]*${pid}[ \t]"`
			if [ -z "${psline}" ]
			then
				echo "orbd is dead but subsys locked"
			else
				echo "orbd (pid ${pid}) is already running"
			fi
		else
			echo "Starting orbd..."
			${ORBD} -defaultdb ${ORBD_DIR} -ORBInitialPort 1050 > /dev/null 2>&1 &
			while [ ! -d ${ORBD_DIR} ]
			do
				sleep 1
			done
			echo $! > ${PIDFILE}
		fi
		;;
	stop)
		if [ -f ${PIDFILE} ]
		then
			pid=`cat ${PIDFILE}`
			psline=`ps -eo "pid,args" | ${GREP} -E "^[ \t]*${pid}[ \t]"`
			if [ -z "${psline}" ]
			then
				echo "orbd is dead but subsys is locked"
			else
				echo "Stopping orbd..."
				kill -15 ${pid}
				sleep 10
				killprocess ${pid}
				rm "${PIDFILE}"
			fi
		else
			echo "orbd is already stopped"
		fi
		;;
	status)
		if [ -f ${PIDFILE} ]
		then
			pid=`cat ${PIDFILE}`
			psline=`ps -eo "pid,args" | ${GREP} -E "^[ \t]*${pid}[ \t]"`
			if [ -z "${psline}" ]
			then
				echo "orbd is dead but subsys is locked"
			else
				echo "orbd (pid ${pid}) is running"
			fi
		else
			echo "orbd is stopped"
		fi
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

