CREATE TABLE Kis (
 id NUMBER(20, 0),
 mcm_id NUMBER(20) NOT NULL,
 name VARCHAR2(64) NOT NULL,
 description VARCHAR2(256),
 domain_id NUMBER(20, 0) NOT NULL,
 CONSTRAINT kis_pk PRIMARY KEY (id) ENABLE,
 CONSTRAINT kis_mcm_fk FOREIGN KEY (mcm_id)
  REFERENCES Mcm (id) ON DELETE CASCADE ENABLE,
 CONSTRAINT kis_domain_fk FOREIGN KEY (domain_id)
  REFERENCES Domain (id) ON DELETE CASSCADE ENABLE
);

CREATE SEQUENCE kis_seq ORDER;
