CREATE TABLE MonitoredElement (
 id NUMBER(20, 0),
 kis_id NUMBER(20) NOT NULL,
 local_address VARCHAR2(64) NOT NULL,
 CONSTRAINT me_pk PRIMARY KEY (id) ENABLE,
 CONSTRAINT me_kis_fk FOREIGN KEY (kis_id)
  REFERENCES Kis (id) ON DELETE CASCADE ENABLE
);

CREATE SEQUENCE monitoredelement_seq ORDER;
