/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syrus_AMFICOM_analysis_dadara_DadaraAnalysisManager */

#ifndef _Included_com_syrus_AMFICOM_analysis_dadara_DadaraAnalysisManager
#define _Included_com_syrus_AMFICOM_analysis_dadara_DadaraAnalysisManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syrus_AMFICOM_analysis_dadara_DadaraAnalysisManager
 * Method:    ana
 * Signature: (I[DDIDDDDDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_syrus_AMFICOM_analysis_dadara_DadaraAnalysisManager_ana
  (JNIEnv *, jobject, jint, jdoubleArray, jdouble, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
