package com.syrus.AMFICOM.configuration;


/**
* com/syrus/AMFICOM/configuration/ComSyrusAmficomConfigurationSchemeElement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-configuration.idl
* 4 Март 2005 г. 18:11:06 MSK
*/

public interface ComSyrusAmficomConfigurationSchemeElement
{
  public abstract com.syrus.AMFICOM.configuration.corba.EquipmentType_Transferable equipmentType ();

  public abstract void equipmentType (com.syrus.AMFICOM.configuration.corba.EquipmentType_Transferable newEquipmentType);

  public abstract EquipmentType equipmentTypeImpl ();

  public abstract void equipmentTypeImpl (EquipmentType newEquipmentTypeImpl);

  public abstract com.syrus.AMFICOM.configuration.corba.Equipment_Transferable equipment ();

  public abstract void equipment (com.syrus.AMFICOM.configuration.corba.Equipment_Transferable newEquipment);

  public abstract Equipment equipmentImpl ();

  public abstract void equipmentImpl (Equipment newEquipmentImpl);

  public abstract com.syrus.AMFICOM.configuration.corba.KIS_Transferable rtu ();

  public abstract void rtu (com.syrus.AMFICOM.configuration.corba.KIS_Transferable newRtu);

  public abstract KIS rtuImpl ();

  public abstract void rtuImpl (KIS newRtuImpl);

} // interface ComSyrusAmficomConfigurationSchemeElement
