package com.syrus.AMFICOM.configuration;


/**
* com/syrus/AMFICOM/configuration/ComSyrusAmficomConfigurationAbstractSchemePort.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-configuration.idl
* 4 Март 2005 г. 18:11:06 MSK
*/

public interface ComSyrusAmficomConfigurationAbstractSchemePort
{
  public abstract com.syrus.AMFICOM.configuration.corba.PortType_Transferable portType ();

  public abstract void portType (com.syrus.AMFICOM.configuration.corba.PortType_Transferable newPortType);

  public abstract PortType portTypeImpl ();

  public abstract void portTypeImpl (PortType newPortTypeImpl);

  public abstract com.syrus.AMFICOM.configuration.corba.Port_Transferable port ();

  public abstract void port (com.syrus.AMFICOM.configuration.corba.Port_Transferable newPort);

  public abstract Port portImpl ();

  public abstract void portImpl (Port newPortImpl);

  public abstract com.syrus.AMFICOM.configuration.corba.MeasurementPortType_Transferable measurementPortType ();

  public abstract void measurementPortType (com.syrus.AMFICOM.configuration.corba.MeasurementPortType_Transferable newMeasurementPortType);

  public abstract MeasurementPortType measurementPortTypeImpl ();

  public abstract void measurementPortTypeImpl (MeasurementPortType newMeasurementPortTypeImpl);

  public abstract com.syrus.AMFICOM.configuration.corba.MeasurementPort_Transferable measurementPort ();

  public abstract void measurementPort (com.syrus.AMFICOM.configuration.corba.MeasurementPort_Transferable newMeasurementPort);

  public abstract MeasurementPort measurementPortImpl ();

  public abstract void measurementPortImpl (MeasurementPort newMeasurementPortImpl);

} // interface ComSyrusAmficomConfigurationAbstractSchemePort
