package com.syrus.AMFICOM.configuration;


/**
* com/syrus/AMFICOM/configuration/ComSyrusAmficomConfigurationSchemePath.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-configuration.idl
* 4 Март 2005 г. 18:11:06 MSK
*/

public interface ComSyrusAmficomConfigurationSchemePath
{
  public abstract com.syrus.AMFICOM.configuration.corba.TransmissionPathType_Transferable type ();

  public abstract void type (com.syrus.AMFICOM.configuration.corba.TransmissionPathType_Transferable newType);

  public abstract TransmissionPathType typeImpl ();

  public abstract void typeImpl (TransmissionPathType newTypeImpl);

  public abstract com.syrus.AMFICOM.configuration.corba.TransmissionPath_Transferable path ();

  public abstract void path (com.syrus.AMFICOM.configuration.corba.TransmissionPath_Transferable newPath);

  public abstract TransmissionPath pathImpl ();

  public abstract void pathImpl (TransmissionPath newPathImpl);

} // interface ComSyrusAmficomConfigurationSchemePath
