package com.syrus.AMFICOM.configuration;


/**
* com/syrus/AMFICOM/configuration/ComSyrusAmficomConfigurationSchemeCableThread.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-configuration.idl
* 4 Март 2005 г. 18:11:06 MSK
*/

public interface ComSyrusAmficomConfigurationSchemeCableThread
{
  public abstract com.syrus.AMFICOM.configuration.corba.CableThreadType_Transferable cableThreadType ();

  public abstract void cableThreadType (com.syrus.AMFICOM.configuration.corba.CableThreadType_Transferable newCableThreadType);

  public abstract CableThreadType cableThreadTypeImpl ();

  public abstract void cableThreadTypeImpl (CableThreadType newCableThreadTypeImpl);

  public abstract com.syrus.AMFICOM.configuration.corba.Link_Transferable thread ();

  public abstract void thread (com.syrus.AMFICOM.configuration.corba.Link_Transferable newThread);

  public abstract Link threadImpl ();

  public abstract void threadImpl (Link newThreadImpl);

} // interface ComSyrusAmficomConfigurationSchemeCableThread
