package com.syrus.AMFICOM.configuration;


/**
* com/syrus/AMFICOM/configuration/ComSyrusAmficomConfigurationSchemePath.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-configuration.idl
* 4 Март 2005 г. 18:11:06 MSK
*/

public interface ComSyrusAmficomConfigurationSchemePath
{
  com.syrus.AMFICOM.configuration.corba.TransmissionPathType_Transferable type ();

  void type (com.syrus.AMFICOM.configuration.corba.TransmissionPathType_Transferable newType);

  TransmissionPathType typeImpl ();

  void typeImpl (TransmissionPathType newTypeImpl);

  com.syrus.AMFICOM.configuration.corba.TransmissionPath_Transferable path ();

  void path (com.syrus.AMFICOM.configuration.corba.TransmissionPath_Transferable newPath);

  TransmissionPath pathImpl ();

  void pathImpl (TransmissionPath newPathImpl);

} // interface ComSyrusAmficomConfigurationSchemePath
