package com.syrus.AMFICOM.configuration;


/**
* com/syrus/AMFICOM/configuration/ComSyrusAmficomConfigurationSchemeCableThread.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-configuration.idl
* 4 Март 2005 г. 18:11:06 MSK
*/

public interface ComSyrusAmficomConfigurationSchemeCableThread {
	com.syrus.AMFICOM.configuration.corba.CableThreadType_Transferable cableThreadType();

	void cableThreadType(
			com.syrus.AMFICOM.configuration.corba.CableThreadType_Transferable newCableThreadType);

	CableThreadType cableThreadTypeImpl();

	void cableThreadTypeImpl(CableThreadType newCableThreadTypeImpl);

	com.syrus.AMFICOM.configuration.corba.Link_Transferable thread();

	void thread(
			com.syrus.AMFICOM.configuration.corba.Link_Transferable newThread);

	Link threadImpl();

	void threadImpl(Link newThreadImpl);

}
