package com.syrus.AMFICOM.configuration;


/**
* com/syrus/AMFICOM/configuration/ComSyrusAmficomConfigurationSchemeLink.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-configuration.idl
* 4 Март 2005 г. 18:11:06 MSK
*/

public interface ComSyrusAmficomConfigurationSchemeLink
{

  /**
  					 * @see com.syrus.AMFICOM.scheme.corba.AbstractSchemeLink#abstractLinkTypeId
  					 */
  public abstract com.syrus.AMFICOM.configuration.corba.LinkType_Transferable linkType ();


  /**
  					 * @see com.syrus.AMFICOM.scheme.corba.AbstractSchemeLink#abstractLinkTypeId
  					 */
  public abstract void linkType (com.syrus.AMFICOM.configuration.corba.LinkType_Transferable newLinkType);

  public abstract LinkType linkTypeImpl ();

  public abstract void linkTypeImpl (LinkType newLinkTypeImpl);

} // interface ComSyrusAmficomConfigurationSchemeLink
