package com.syrus.AMFICOM.configuration;


/**
* com/syrus/AMFICOM/configuration/ComSyrusAmficomConfigurationSchemeElement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-configuration.idl
* 4 Март 2005 г. 18:11:06 MSK
*/

public interface ComSyrusAmficomConfigurationSchemeElement
{
  com.syrus.AMFICOM.configuration.corba.EquipmentType_Transferable equipmentType ();

  void equipmentType (com.syrus.AMFICOM.configuration.corba.EquipmentType_Transferable newEquipmentType);

  EquipmentType equipmentTypeImpl ();

  void equipmentTypeImpl (EquipmentType newEquipmentTypeImpl);

  com.syrus.AMFICOM.configuration.corba.Equipment_Transferable equipment ();

  void equipment (com.syrus.AMFICOM.configuration.corba.Equipment_Transferable newEquipment);

  Equipment equipmentImpl ();

  void equipmentImpl (Equipment newEquipmentImpl);

  com.syrus.AMFICOM.configuration.corba.KIS_Transferable rtu ();

  void rtu (com.syrus.AMFICOM.configuration.corba.KIS_Transferable newRtu);

  KIS rtuImpl ();

  void rtuImpl (KIS newRtuImpl);

}
