package com.syrus.AMFICOM.configuration;


/**
* com/syrus/AMFICOM/configuration/ComSyrusAmficomConfigurationAbstractSchemeLink.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-configuration.idl
* 4 Март 2005 г. 18:11:06 MSK
*/

public interface ComSyrusAmficomConfigurationAbstractSchemeLink
{
  public abstract com.syrus.AMFICOM.configuration.corba.AbstractLinkType_Transferable abstractLinkType ();

  public abstract void abstractLinkType (com.syrus.AMFICOM.configuration.corba.AbstractLinkType_Transferable newAbstractLinkType);

  public abstract AbstractLinkType abstractLinkTypeImpl ();

  public abstract void abstractLinkTypeImpl (AbstractLinkType newAbstractLinkTypeImpl);

  public abstract com.syrus.AMFICOM.configuration.corba.Link_Transferable link ();

  public abstract void link (com.syrus.AMFICOM.configuration.corba.Link_Transferable newLink);

  public abstract Link linkImpl ();

  public abstract void linkImpl (Link newLinkImpl);

} // interface ComSyrusAmficomConfigurationAbstractSchemeLink
