package com.syrus.AMFICOM.configuration;


/**
* com/syrus/AMFICOM/configuration/ComSyrusAmficomConfigurationSchemeProtoElement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-configuration.idl
* 4 Март 2005 г. 18:11:06 MSK
*/

public interface ComSyrusAmficomConfigurationSchemeProtoElement
{
  public abstract com.syrus.AMFICOM.configuration.corba.EquipmentType_Transferable equipmentType ();

  public abstract void equipmentType (com.syrus.AMFICOM.configuration.corba.EquipmentType_Transferable newEquipmentType);

  public abstract EquipmentType equipmentTypeImpl ();

  public abstract void equipmentTypeImpl (EquipmentType newEquipmentTypeImpl);

} // interface ComSyrusAmficomConfigurationSchemeProtoElement
