package com.syrus.AMFICOM.configuration;


/**
* com/syrus/AMFICOM/configuration/ComSyrusAmficomConfigurationSchemeCableLink.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idl_v1/idl/scheme-configuration.idl
* 4 Март 2005 г. 18:11:06 MSK
*/

public interface ComSyrusAmficomConfigurationSchemeCableLink
{

  /**
  					 * @see com.syrus.AMFICOM.scheme.corba.AbstractSchemeLink#abstractLinkTypeId
  					 */
  public abstract com.syrus.AMFICOM.configuration.corba.CableLinkType_Transferable cableLinkType ();


  /**
  					 * @see com.syrus.AMFICOM.scheme.corba.AbstractSchemeLink#abstractLinkTypeId
  					 */
  public abstract void cableLinkType (com.syrus.AMFICOM.configuration.corba.CableLinkType_Transferable newCableLinkType);

  public abstract CableLinkType cableLinkTypeImpl ();

  public abstract void cableLinkTypeImpl (CableLinkType newCableLinkTypeImpl);

} // interface ComSyrusAmficomConfigurationSchemeCableLink
